### ISSUE TITLE
Create build package

### ISSUE THREAD

**Issue by aomarks** [breadboard-ai/breadboard#1006]
The next step from https://github.com/breadboard-ai/breadboard/issues/539 is creating a `build` package.

The idea here is to create a package that contains only what is needed for writing boards, defining node types, and publishing kits, (and I think serializing boards to BGL?), but not running them. The main reason for that is that we don't want our ecosystem's re-usable libraries to be tied to specific runtime implementations, or overly constrained to specific versions of them; (kind of like how you wouldn't want to publish a JS library that literally depends on Node or Chrome in its dependency graph).

I also think this is an opportunity to refine the building aspect of the API, so I'm planning with this package to have a variation of the current `board` API which is compatible with the current `breadboard` tools, but adds a bunch of additional type-safety, and also has a slightly different shape that I believe is more amenable to getting that strong type-safety.

**Comment by Mearman** [comment]
re: https://github.com/breadboard-ai/breadboard/actions/runs/8256291136/job/22584686192#step:8:27
@aomarks looks like an issue introduced by https://github.com/breadboard-ai/breadboard/pull/571. I can have a look if you haven't had a chance by the time you clock off and I clock in.

**Comment by aomarks** [comment]
This is done
