### ISSUE TITLE
Combine tutorial chapters into one Replit project

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#102]
Currently, the experience of jumping between chapters is jarring, since every new chapter is a new Replit project that needs its secrets setup and now there are two places to keep track of: the tutorial doc and the Replit project itself.

Maybe if we combined all the chapters into one Replit project, where the samples and the tutorial and interwoven, it would be a better experience?

**Comment by dglazkov** [comment]
Relevant in context of #171.

**Comment by Meggin** [comment]
FYI, I started combining chapters in a local branch before the New Year, and I wonder if maybe there is a much simpler approach here. Perhaps there's a 5-minute get started that is super simple, and then a 'build a chat bot' that is end-to-end. WDYT?

**Comment by dglazkov** [comment]
Sounds great! One wrinkle is that we're in the midst of switching to the new syntax, which made most of the tutorial obsolete. Maybe we could put our minds together and figure out what the new tutorial should look like?

**Comment by dglazkov** [comment]
Folding this into #509.
