### ISSUE TITLE
review Will's friction log to identify and list new examples required and changes to existing examples

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#1028]
- see:
    - https://docs.google.com/document/d/1-FAofW-q8O4mmOoj_H4a2a7zlHnzw75ABke_mf6WEk0
    - https://github.com/breadboard-ai/breadboard/issues/693

**Comment by TinaNikou** [comment]
I think it could potentially be useful to do the following:
1) Add a new example demonstrating using breadboard proxy
2) Explicitely specify board input/output types

Following a meeting with Will, Joe noted discussion of the input, output and schema types, and we agreed that it'd be useful to add a new example to highlight the types and that, without explicit types, then you can get an error that properties don't exist in some instances.
