### ISSUE TITLE
[FR] Add metadata to the breadboard schema

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1033]
In the [published schema](https://raw.githubusercontent.com/breadboard-ai/breadboard/@google-labs/breadboard-schema@1.3.0/packages/schema/breadboard.schema.json) we don't currently admit `metadata` as a property on `node`. Not a massive dealbreaker, but it'd be nice if VSCode didn't show yellow squiggly warnings 😄

**Comment by dglazkov** [comment]
@Mearman should it not be generated from the types automatically? Has that change landed?

**Comment by Mearman** [comment]
it hasn't been merged yet has it?

**Comment by dglazkov** [comment]
> it hasn't been merged yet has it?

Set the auto-merge to "on" 🚢

**Comment by Mearman** [comment]
I just need to fix the conflict in the package lock XD

**Comment by Mearman** [comment]
@paullewis what is the shape of the metadata at the moment?

**Comment by Mearman** [comment]
@dglazkov auto-merge disabled by pushing to fix the merge conflict

**Comment by dglazkov** [comment]
Should work now!
