### ISSUE TITLE
Add reflection to nodes

### ISSUE THREAD

**Issue by seefeldb** [breadboard-ai/breadboard#107]
[This is a continuation of [this discussion of describe](https://github.com/google/breadboard-ai/issues/26)]

In addition to the regular handler, each node implementation should export a reflection function that describes its inputs and outputs.

This is useful in e.g.
 - a visual editor, which can understand nodes in this way, especially if the inputs or outputs depend on the configuration of the node (or even incoming data!)
 - self describing APIs, e.g. when exposed as cloud function
 - as a way to express errors in a graph and iterate towards resolving those (here, missing inputs should trigger an `$error` output (see google/labs-prototypes#129) that is the same as calling reflection with the current inputs and wired schemas, see below)

It takes three parameters, all optional:
1. inputs, which are inputs as if they were passed to the node
2. input schemas, the currently expected schema of these and other inputs
3. output schemas, the currently expected output schemas

The output of the reflection function contains:
1. input schemas, including indicating which are required – note that this can depend on the provided inputs! (see below)
2. output schemas
3. how complete the response is, which is one of
    1. calling with the inputs is valid
    2. supplying all inputs marked as required will be sufficient, assuming they match the schema
    3. the inputs are not complete yet and will depend on supplying at least some of `[list of missing inputs]`

For nodes that have fixed inputs and outputs this boils down to schema validation and we should supply conveniences to generate reflection automatically, ideally from Typescript schemas that are used to implement the node itself.

When input or output schemas are supplied to the call, besides those actually selecting different behaviors in some cases (see below), reflection should verify that inputs conforming to those schemas are valid and/or that outputs will conform to the supplied schema. The return value should only cover the part of the schema that is actually used. This allows the input  data to contain more data / only a subset of the data from the output to be used. But it also allows a higher level validator to make sure that it's fine to ignore the other parts, which is not always the case (e.g. ignoring the second part of `Restaurant { name: string, closedPermanently: boolean }` might be bad). LLMs might be reasonably good at detecting such cases, FWIW.

Examples of more complex scenarios:

- `promptTemplate`: The actual inputs depend on the `{{ variables }}` defined in the template. So you can imagine this sequence of calls:
   1. empty call --> input schema describing `template` as required (and the output schema for `prompt`, which will be the same for all subsequent calls)
   2. providing template that contains `{{ foo }}` --> input schema describing `template` and `foo` and indicating that supplying a string for `foo` will be sufficient
   3. (optional:) calling with `template` and `foo` --> same input and output schema, but indicating that this would be a valid call
- `jsonata`: The actual outputs depend on the query:
   1. empty call --> input schema describing `expression`, `json` and `raw` + union of possible outputs (TODO: since `raw` has a default value, technically we should assume `result` unless `raw = true` will be provided)
   2. calling with inputs for `expression` and setting `raw` to true --> _ideally_ replying with both the input and output schema defined by the expression.
   3. ...
- `runJavascript`: Function implies expected parameters
- `passthrough`: Supplying either input or output schema implies the other
- etc.

To be discussed: Clearly some of these require advanced parsing of the workload, which might be highly non-trivial to implement. Should we instead call an LLM to provide a reasonable guess? They are pretty good at understanding e.g. code or jsonata queries, but will not always be correct. And it would seem odd to hardcode a specific LLM into nodes. So maybe instead of saying "I don't know", a node can reply with a prompt to an LLM that would answer the question. And maybe we add a way to call reflection again with the answer from the LLM, so that it can turn that into a proper response for us (or even ask another question).

This can also be called in other orders, especially if `$role` is provided (see google/breadboard-ai#56):
- `promptTemplate`: This time the template is the missing piece:
   1. Call with `foo`, `bar` and other given inputs --> input schema describing `template` with a description that says that the template can contain `{{foo}}` and `{{bar}}` (and same output as above)
   2. Given `$role` and the new description ask an LLM to write a template, call again with that template --> if valid, respond as such, otherwise provide feedback such as missing inputs, e.g. if the LLM hallucinated other template variables
- `runJavascript`, `jsonata`, etc. could all work the same way
- We could even start with just `$role` and go with hallucinated inputs and then suggest nodes that provide those inputs. This would be a way to bootstrap graph generation from a few key nodes, such as a template.

**Comment by dglazkov** [comment]
Victory 🚢  Let's track any remaining bits separately.
