### ISSUE TITLE
[FR] Click to add node in web UI

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#1086]
Was unsure if this was existing expected behaviour or not, but after https://github.com/breadboard-ai/breadboard/pull/1085 I've confirmed. It would be very nice to be able to just "click to add" on the items as well as being able to drag them in.

Also reminded me that https://github.com/breadboard-ai/breadboard/issues/897 is now resolved. But it would be very nice to also be able to pin the toolbox open.

**Comment by paullewis** [comment]
I made it so you can double click. It currently adds it at [0, 0] in the graph because I can't think of a better location for a new node 😄 – hope that helps!
