### ISSUE TITLE
[FR] Be able to request a blank board from Breadboard itself.

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1139]
Currently I use a [hardcoded blank board](https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-web/src/providers/blank-board.ts) when creating a new board via a Provider. It feels like this could get out of sync with Breadboard's expectations. Should we have a `createBlankBoard` method we can call against `packages/breadboard`?

**Comment by dglazkov** [comment]
that sounds right!

**Comment by Mearman** [comment]
this is basically what I was using `new Board()` for. can't remember when I was talking about this functionality in the object syntax
