### ISSUE TITLE
Support streaming progress updates to e.g. render a progress dashboard

### ISSUE THREAD

**Issue by seefeldb** [breadboard-ai/breadboard#114]
Especially for long running tasks, e.g. parsing, chunking, embedding and indexing documents for later semantic retrieval, it would be great to show the user a progress UI. And ideally the UI is rather generic and doesn't depend on the details of the breadboard, so that the UI doesn't break if details like e.g. the chunking strategy are changed.

A couple observations:
- probes seem ideal for this, but without any extra work, the UI layer would have to put together the meaning of different signals (e.g. extracting the current file from a "loading file" probe and then associating later chunking events with that).
- the nodes that do the work tend to have little broader context (which is a good thing)
- sometimes even the graphs won't have the context, e.g. when they were passed in as lambda to do a particular job: an embedding lambda won't know that it's operating on chunks, etc.

Possible approaches:
- Annotate in the graph what a particular node does. So you get the structured data from the node itself + an annotation from the graph about the specific role. That is reminiscent of google/breadboard-ai#56 and the `$role` proposal there, except that this would be more like a schema than natural language (and for google/breadboard-ai#56, natural language is more appropriate).
- Similarly annotate the role invoked graphs play, which is where e.g. the filename might be associated with finer grained operations: The breadboard that goes through all the files calls another breadboard to index one, annotating that call with the filename itself. This requires (a) collecting these annotations along the path of a nested probe and (b) allow variable expansion in the descriptions, so picking a template language, etc.
- The risk is that beyond something very basic, this starts to grow to a whole framework on its own.
- Hence, another option would be to use regular breadboard nodes to annotate the probe data.
  - And then either use regular outputs or newly sent probe events to get the data out to the UI.
     - One possibility would be to just treat it like any other output wire, maybe with a "event:<type>" name that selects events by type? And maybe add a node that just creates a probe event with its input and hence of a given type?
     - Whether to reissue events or just use regular outputs: If we use regular outputs then each caller has to add logic to pass event data up. OTOH, introducing this out of band communication channel might be abused. That said, it's a little reminiscent to google/breadboard-ai#106 's `$error` handling.
  - Such listening by nodes on other nodes should probably happen at the end of the listening chain, so that .preventDefault still works as expected.

Nest step: Flesh out an example
Also requires resolving google/breadboard-ai#103 (streaming of nested graphs).

**Comment by dglazkov** [comment]
We do this now! Victory 🚢
