### ISSUE TITLE
[FR] Show better errors when a board load fails

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1142]

**Comment by paullewis** [comment]
Also worth having an empty / unloaded screen with an option to spin up a new blank board

**Comment by dglazkov** [comment]
Related, there's a fun edge case: sharing links. For example:

This one is accessible to all:
- https://breadboard-ai.web.app/?mode=build&board=%2Fgraphs%2Fboard-as-function.json

But this one is only local to me:
- https://breadboard-ai.web.app/?mode=build&board=file%3A%2F%2Ffsapi%7Eapi%2FcreateChatCompletion.json

**Comment by paullewis** [comment]
Do we make `shareable` a feature of a provider?

**Comment by dglazkov** [comment]
That would give us a way to at least display a reasonable error message!
