### ISSUE TITLE
Web schema editor doesn't update node ports

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#1254]

**Comment by paullewis** [comment]
Can you tell me more?

**Comment by Mearman** [comment]
when adding a property on an output node, for example, the ports that are shown aren't updated to reflect the updated schema

**Comment by paullewis** [comment]
I can't repro that on my end yet. If I go to a blank board, click on the output node, hit the + button in the top right corner it adds `property-2` and that appears as a node in the graph. Are you getting a different outcome?

**Comment by dglazkov** [comment]
Should be fixed now, this one was my bad 🤦🏻. Please re-open if that's not the case.
