### ISSUE TITLE
[FR] Use "*" port as a "Drop zone" for new ad-hoc wires.

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#1255]

**Comment by paullewis** [comment]
I'm unable to repro. What I tried:

1. Get a blank board, add a new property to input (probably `property-2`)
2. Try to wire `input-1.property-2` to `output-2.*`
3. Get an error: "A specific input port cannot be connected to a "*" output port"

Can you tell me how to repro it from your side?

**Comment by Mearman** [comment]
this one was more a request for a new behaviour. when **trying** to wire up as above, it'd be nice if an appropriate port and schema entry was created and the wire connected to there rather than the *

**Comment by dglazkov** [comment]
Ohh, I think you're proposing to reuse the "*" as a "Drop zone" for new ad-hoc wires. Is that right?

**Comment by Mearman** [comment]
Yes! That's a far better way of describing it
