### ISSUE TITLE
Create Schema Kit

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#1259]
> Got it. My spidey sense tells me that this is probably a different kind of node. Maybe a util node that takes a JSON object and produces a schema for it? Let's not add this bit to the fetch node.

- @dglazkov in https://github.com/breadboard-ai/breadboard/pull/1253#discussion_r1542111797

**Comment by dglazkov** [comment]
Or maybe add another node to the JSON kit?

**Comment by Mearman** [comment]
I considered it, though it can be used with any value, not exclusively JSON. And I can forsee wanting to add more schema manipulation nodes.

This somewhat comes back to what I mentioned ages ago about being able to declare and include standalone nodes.

I also have a feeling this relates to the node logic signature definition ponderings.

**Comment by dglazkov** [comment]
It's JSON Schema, so it makes sense to put it in JSON kit.
