### ISSUE TITLE
Pressing enter on a text box in the port node configuration deletes the port

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1268]
When trying to configure the default value of a port, if you press enter while in the text box it will invoke the "delete" button. See GIF

![ScreenFlow](https://github.com/breadboard-ai/breadboard/assets/45510/29293e42-bd65-4fb8-a5df-931ad44350af)

I'd expect `Enter` to not do anything

**Comment by paullewis** [comment]
I think it's a missing `type="button"` – hopefully this resolves it!
