### ISSUE TITLE
[FR] Allow renaming of subgraphs

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1343]
Feels like a useful thing to have at some stage. Falls out of #1309 because I wanted to offer a rename option, but I didn't really fancy adding a new subgraph and removing an old one as a two-pass. wdyt, @dglazkov?

**Comment by dglazkov** [comment]
I just had a thought: what if we more-or-less auto-generate graph ids (`graph-1`, `graph-2`, etc.) and use the graph title as the name that the user enters when they create a new graph? This way, they can freely rename them and retain integrity of the references to it?

**Comment by paullewis** [comment]
Super idea. Wonder if we should be doing the same when someone drops a node onto the editor. We don't need to show the ID really.

**Comment by dglazkov** [comment]
victory?

**Comment by paullewis** [comment]
Yeah, I guess so, since we're going to start hiding the actual IDs of the subgraphs.
