### ISSUE TITLE
[FR] Restore `multichange` visual info

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1346]
So we need to figure out how we bring back the post-Dagre layout visual storing without the metadata change bumping the version. Right now if you:

1. load a graph without layout data
2. move one node
3. jump to a subgraph
4. go back to the main graph

You will likely see layout issues. This is because Dagre has re-run layout for the graph minus the one that was moved. Previously we emitted the multilayout event after Dagre did its work so that all nodes had layout info. Think I need a way to push visual changes without the graph version being bumped?

**Comment by dglazkov** [comment]
This is probably not the final shape, but the `GraphChangeEvent` now has a `visualOnly` boolean property which is `true` when the changes that occurred were only in `metadata.visual`.
