### ISSUE TITLE
[FR] Enable highlighted node ID scoping

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1348]
To this point we only showed the top level graph so we could assume that you'd only ever see those nodes. Now, however, you could be looking at a subgraph and it _may_ contain nodes with IDs that match the main board, which means you'd see the highlight when you shouldn't have. 

I've somewhat worked around the node highlighting when we're running the graph by simply resetting the highlight ID when you move between subgraphs, but that's definitely incomplete as `output-2` – say – would highlight for both the main graph and any subgraphs.

**Comment by dglazkov** [comment]
This is a really nice puzzle. 🧠

**Comment by dglazkov** [comment]
PTAL, the basic idea is that now, the `InspectableRun` exposes the `currentNodeEvent` property, which returns the latest node event during the run. This event contains the graph and the node descriptor, which lets us orient ourselves and decide whether or not to highlight the node.

**Comment by dglazkov** [comment]
It gets a bit gnarly here:

https://github.com/breadboard-ai/breadboard/blob/ae79e4a89ba764d221e591cb5613059c381e4cdd/packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts#L236-L250

But my hope is that eventually, we'll teach the machinery to speak in terms of graph URLs, and it will all get better (waves hands optimistically)
