### ISSUE TITLE
Preview keeps asking for secrets

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1351]
For some reason, when running the preview of a board, it keeps asking for secrets.

**Comment by paullewis** [comment]
Ah, yeah I didn't wire in secrets yet 🤦🏻‍♂️

**Comment by paullewis** [comment]
Hmm, should the preview match the main editor and only store secrets if the setting is enabled, or should it be more as we had it where it stores eagerly?

**Comment by dglazkov** [comment]
if the settings isn't available in `&embed`, then probably the eager storing is good. Right?

**Comment by paullewis** [comment]
It's on the same origin so it has access to the same settings if we want it to... Having slept on it I think that's what I'll do; have it match the existing non-embed behavior.
