### ISSUE TITLE
Bugs in edge management

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1407]
1. Start with `blank.json`, with `input.text -> output.text` set. Now create `input.text -> output.*`. It creates a duplicate edge to the `input.text -> output.text`, but with `constant: false`.
3. Same with `input.text -> output.control`.
4. Create `input.* -> output.control` and it creates `input.* -> output.*`, though the edge is actually: `{from: 'input-1', to: 'output-2', out: '*', in: '', constant: false}`

I _think_ these are happening in the Editor API, but I've not had chance to dig in yet. cc @dglazkov

**Comment by paullewis** [comment]
I had a bit of a prod, and they do seem to be in the Editor API 👍🏻

**Comment by dglazkov** [comment]
I figured it out. We need a "no change" graph change event, when an error occurred, and we need to redraw the graph, but there's no change to graph object identity.

**Comment by dglazkov** [comment]
like, maybe `graphchangerejected` event.

**Comment by paullewis** [comment]
We should be building the graph from the object (with some caching on a few bits), so if we aren't that's a bug in the Visual Editor. I did see that the graph in bb-main had 2 edges after the change, so it seemed like the descriptor was carrying erroneous edges. Are you seeing something different?

**Comment by paullewis** [comment]
We do need to emit an updated descriptor, that's true, because we need the graph to refresh with whatever is the latest. I'm just wondering if the failed edit is only partially failing, or is it that we're holding onto the graph that we submitted to the API (and which was rejected)?

**Comment by dglazkov** [comment]
This is a bug that I introduced here (among many others 😆):
https://github.com/breadboard-ai/breadboard/commit/65d869bf62601036ec43342f0baca4fef0605b8b

By removing all the calls to `#updateGraph`, I removed the way to notify the editor in  situations where the proposed graph change was rejected, whether due to an error or simply because it is redundant (like, the same edge already exists).

**Comment by dglazkov** [comment]
There's also muddiness around `constant` that I still need to figure out.

**Comment by dglazkov** [comment]
Okay, I think it's all fixed nao 🤞🏻
