### ISSUE TITLE
Number inputs are acting weirdly

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1414]
I can't seem to set examples for them and when I try to set defaults, they don't do what I want them to do... Investigating...

**Comment by paullewis** [comment]
I can take a look tomorrow if you want?

**Comment by dglazkov** [comment]
sure!

**Comment by paullewis** [comment]
Okay, so I've had a bit of a look. I've taught the Array Editor about how to deal with numbers, and I've switched on examples for number types. The `default` thing, though, I couldn't replicate, at least not directly. I wonder if the fact that [the schema always denotes it as `string|undefined`](https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard/src/types.ts#L119) is part of the issue, though? I'm guessing it should maybe be `NodeValue`?

**Comment by dglazkov** [comment]
oooh that was a good one. found it. fix incoming.
