### ISSUE TITLE
[breadboard-web] Can we add the ability to select and copy text from the Run history

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1419]
<img width="418" alt="Screenshot 2024-04-15 at 11 06 24" src="https://github.com/breadboard-ai/breadboard/assets/45510/26f11cdf-a6aa-46fc-8d94-5176aacf15c2">

I need to copy and paste the data for another run, can we get the ability to right-click and copy things from text boxes, right now I can't even select the text to copy it.

**Comment by paullewis** [comment]
Text selection should be on as of #1423 👍🏻
