### ISSUE TITLE
Visual Editor "Super Worker" Preset MVP ☂️

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1445]
A preset that helps significantly streamline the process for creating boards with "super agent"/specialist.  

The preset includes flags like
a) which nodes/kits need to be available,
b) which ports are shown,
c) which items are configurable would be the likely candidates.

The values of those flags will be carried in the board's metadata so that someone opening the board will have see the UI as the author had it (Visual Editor versioning notwithstanding).

We will also look to find ways to enumerate "mid stages" for those flags, so that it's not Easy vs Hard, but more of a progressive reveal. This might mean we have multiple variants of – say – node and kit pickers which are instantiated based on the flag's values.

Here's a to do list for getting to an MVP of something like that:

- [x] #1600
- [ ] #1548
- [x] #1601
- [x] #1480
- [x] #1583
- [x] #1471
- [x] #1581
- [x] #1597
- [x] #1475
- [x] #1485
- [x] #1472
- [x] #1463
- [x] #1470

**Comment by dglazkov** [comment]
Maybe something like "expand" chiclet for each node? I dunno.

**Comment by donsbach** [comment]
Taking a look at the details of these Issues, but I'd like us to implement Stop run. It's very confusing to have to complete the run or reload the board to see a change.

**Comment by dglazkov** [comment]
Added to the list!

**Comment by dglazkov** [comment]
capturing what @paullewis posted elsewhere:

The "mode" is actually a "preset" that helps significantly streamline the process for creating boards with "super agent"/specialist.  

Includes flags like
a) which nodes/kits need to be available,
b) which ports are shown,
c) which items are configurable would be the likely candidates.

We will code in those flags and create a preset for them. The values of those flags will be carried in the board's metadata so that someone opening the board will have see the UI as the author had it (Visual Editor versioning notwithstanding).

We will also look to find ways to enumerate "mid stages" for those flags, so that it's not Easy vs Hard, but more of a progressive reveal. This might mean we have multiple variants of – say – node and kit pickers which are instantiated based on the flag's values.

**Comment by dglazkov** [comment]
Declaring victory 🚢
