### ISSUE TITLE
Sort node types in InspectableKit

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1459]
Currently curry is the last node in the list, but logically, it should be somewhere at the top (alphabetic sort seems like a reasonable expectation)

![image](https://github.com/breadboard-ai/breadboard/assets/1934/df71ef78-ccd4-49f8-b13f-cd1ede5245f9)

Let's sort node types in InspectableKit to make nodes easier to find in the node selector.

**Comment by PaulKinlan** [comment]
big +1 to alphabetical ordering. Can we add a description to them too?
