### ISSUE TITLE
Make project more legible to newcomers

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#146]
Right now, the Breadboard project is a collection of packages in a monorepo. It takes a bit of time to piece together all the bits and get a full picture of what's going on -- a tax on newcomers.

Let's make a first pass at making the Breadboard project a bit easier to comprehend and get started. We need:

- [ ] A map of all packages -- how they relate to each other and what's what
- [ ] A written guide to the project
- [ ] Perhaps deprecating/moving some packages (see google/breadboard-ai#143 as an example)
- [ ] A refresh to [DEVELOPING.md](https://github.com/google/labs-prototypes/blob/main/DEVELOPING.md)  to reflect the latest changes and add relevant links (maybe a Breadboard-specific one?)
- [ ] {insert item}

**Comment by aomarks** [comment]
We've moved to https://github.com/breadboard-ai/breadboard

**Comment by dglazkov** [comment]
Declaring victory here, splitting off remaining work to #510, #509, etc.

**Comment by dglazkov** [comment]
🚢
