### ISSUE TITLE
Make "easy mode" switchable and configurable

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1470]
Switchable:
- we should be able to switch between easy and hard mode. Maybe just a global setting for now.

Configurable:
- It seems like maybe there will be other settings that come bundled with the switch, like a filter from #1463. When I switch to "easy" mode, all those go into effect as well
- There may be many configurations eventually: for instance, one for agent editing, another for generated image editing (like ComfyUI), etc. For now, let's figure out how to make one, but keep the notion of many configs in mind.
- We also need a way to pass configurations along to others. The ideal experience is that I just share a link with you, and you get my config. But not sure of the final shape.

**Comment by donsbach** [comment]
My $0.02, let's stay clear of "easy" and "hard"... it's not easy and hard, it's a lite editor and a full editor. We might want to simplify the full editor with more progressive reveal.

**Comment by dglazkov** [comment]
Is it a "view" on an editor, where this is a preset that is customized for a particular purpose?

Or is it a property of a graph? "Best viewed as". If I am working on two files, one is the "full editor" mode, deep, classic Breadboard. One is the "agent designer" mode. Per URL? Remember last?

Select per board?

**Comment by paullewis** [comment]
#1498 is enabling a lot of these. Just needs a "preset" adding which sets them all at once :)

**Comment by dglazkov** [comment]
Declaring victory 🚢 , tracking the "preset" part in #1548
