### ISSUE TITLE
When using the gemini vision kit, I'd like to be able to add a file from the file system from the Web UI

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1476]
Current I can only select a Canvas or WebCam

**Comment by PaulKinlan** [comment]
Just as an update - while the UI let's me configure an input to be an file that can be uploaded, the runtime UI doesn't change to a picker (it just leaves a text input).

<img width="892" alt="Screenshot 2024-04-30 at 10 53 15" src="https://github.com/breadboard-ai/breadboard/assets/45510/82b6906c-5699-49c3-8e51-1ebb07fb5408">

<img width="893" alt="Screenshot 2024-04-30 at 10 53 53" src="https://github.com/breadboard-ai/breadboard/assets/45510/a2402820-34c0-4634-9cff-69c166e9ae1a">

cc @paullewis

**Comment by paullewis** [comment]
Ah yes, that's definitely a TODO of mine for this week. For now, just leave it as an "Any" and it should spin up the LLM Content Input

**Comment by PaulKinlan** [comment]
> Ah yes, that's definitely a TODO of mine for this week. For now, just leave it as an "Any" and it should spin up the LLM Content Input

Good to know.

**Comment by paullewis** [comment]
Started working on a fix for you now though 👍🏻

**Comment by dglazkov** [comment]
Victory 🚢
