### ISSUE TITLE
Add ability to collapse the node to minimal view

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1485]

**Comment by dglazkov** [comment]
In collapsed view, what are my default ports? When I drag from that edge to another, what edge am I actually dragging?

**Comment by paullewis** [comment]
For now these ports aren't editable, but that's something we could revisit? Other than that, though, we could declare victory if you want?

**Comment by dglazkov** [comment]
Victory!!! 🚢
