### ISSUE TITLE
What do we do about all the harnesses?

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#159]
As of now we've gained three harnesses in `breadboard-web`:

- Worker harness (default), which runs the board in a worker and proxies some nodes out.
- Main thread harness, which runs the board on the main thread (simple!)
- Server proxy harness, which runs the board on the main thread and proxies some nodes to a node proxy server.

All have their own pros and cons. Main thread harness is simple and likely easiest to debug and mess around with. Worker harness s likely the smoothest. Server proxy harness allows not needing API keys.

We should probably decide:

- [ ] which should be the default for deployment at https://breadboard-ai.web.app/
- [ ] which should be the default for local development
- [ ] whether or not we should have a UI for switching them and what should it look like
- [ ] if we need more harnesses and why

@paullewis @seefeldb

**Comment by PaulKinlan** [comment]
I completely forgot about this thread when asking about the [Harnesses](https://discord.com/channels/1138546999872999556/1138554749537484810/1184817465830670366).

They look really useful. When I'm building projects outside of the monorepo and I want isolation from the UI main-thread, I essentially implement something like this. For [TheCritic](https://github.com/GoogleChromeLabs/breadboard-samples/blob/main/samples/TheCritic/src/worker.ts) I wrapped the Board in a class that would let me add more lambda's in and then exposed that class from the worker using comlink. 

I had originally looked to use the worker harness, but the harnesses had dependencies on Kits that I wasn't using.
