### ISSUE TITLE
[ui] Less obtrusive diagnostic outputs

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#160]
Diagnostic / debug outputs from – say – LLMs are displayed prior to the output node. It's likely that we can make this a part of the output node itself rather than a separate node.

Might need some wiring changes to embed the diagnostic info into the output node itself, maybe? I looked at the output info coming through and it does seem like it's only the first candidate. 

/cc @dglazkov

**Comment by dglazkov** [comment]
Declaring victory here. A fully fledged debugger has emerged 🚢
