### ISSUE TITLE
Editing an `llm-content` text part removes focus 

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1623]
To repro:

- go to Specialist Testing Grounds
- click on Outline Writer
- try to edit the text part
- the text part will loses focus on every input

I tried to spelunk and I can't figure out easily why that happens.

I thought it might be because I added markdown rendering, but it still reproduces without it.

**Comment by dglazkov** [comment]
Oh interesting! it looks like this happens with all the inputs in the Node Details. When I try to edit the input schema, I get the same result.

Let me look real quick....

**Comment by paullewis** [comment]
I think it's because the schema update triggers a re-render. It is likely to do with the guard in the UI controller and/or the shouldUpdate in the node info

**Comment by paullewis** [comment]
It's really tricky to get right because we don't want it to re-render when you type, but we do when you change edges or add/remove properties. In fact the problem is probably the @breadboardnodeupdate listener I added today in the UI controller. It probably needs to be a bit more discerning about whether it qualifies for a re-render.

**Comment by dglazkov** [comment]
https://github.com/breadboard-ai/breadboard/commit/4e181089ef87e6a67dd51ee2f81797a86e77f897 this one is what made it go kablooey.

**Comment by dglazkov** [comment]
I wonder if the Editor API "graphchange" event could help with this somehow.

**Comment by paullewis** [comment]
I'll take a fresh pass at this now

**Comment by dglazkov** [comment]
> I realised that we can listen directly for schema changes. I don't think we can use the graphchange event because it responds to all changes, and here we only want to know when edges and schema changes occur. I suppose we could consider expanding on the `GraphChangeEvent` to let us know exactly what changed internally?

This sounds like a really good feature. Basically, a flag on the event that is true when the event changes the shape of the graph? WDYT?
