### ISSUE TITLE
Bring back the node type display

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1624]
Currently, once we edit the name of the node, we no longer have any indication of what type of a node it is. We probably should somehow still display the node type

**Comment by paullewis** [comment]
Ah, good point.

**Comment by donsbach** [comment]
I had a pattern that was "Title (nodetype)" for this reason
<img width="257" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/a30019a6-cb9b-4e56-94b2-f49b0acf89b3">

**Comment by paullewis** [comment]
I need to revisit the exact styling of the title here, but will move forward with other pieces for now.
