### ISSUE TITLE
🐞 LLM_content doesn't work when a Default is supplied

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1627]
When the schema for LLM_content has a default value on an input, it renders with no editable area:

<img width="350" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/f365838c-74ca-4cf0-a579-8862d0ee65e0">

**Comment by paullewis** [comment]
We didn't have the LLM content input live for defaults before now. Now that we do this should be easier.
