### ISSUE TITLE
🐞 Losing \n in LLM_content "txt" chunks

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1628]
\n are removed from txt chunks in LLM_content when i remove node focus and come back:

This…
<img width="474" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/5e68583b-45f6-4dfc-9175-aa3ff130522e">

Becomes this…
<img width="469" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/3d3a4f8c-de91-47ca-a407-713c35bcac7a">

**Comment by donsbach** [comment]
This margin issue might be connected... 
![image](https://github.com/breadboard-ai/breadboard/assets/123408/b57c1288-cedc-4430-8891-194f40e0ab9e)

**Comment by paullewis** [comment]
This was a good one... by which I mean it was quite the wrangle. It should be better now, but lmk if not.
