### ISSUE TITLE
[Feature request] Include icons in node descriptors from Inspect API

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1647]
Currently we have the icons in the metadata for a _kit_, but the descriptor for a node from the Inspect API doesn't currently carry the icon. I could do a lookup in the editor when we process the graph, but I wonder if we want to do that resolution at the Inspect API? It would make life easier because I wouldn't need to create an extra interface or carry two parallel pieces of data over to the graph.

@dglazkov, wdyt?

**Comment by dglazkov** [comment]
Yes!

The `InspectableNode` needs to grow a `type()` method, which returns a proper `InspectableNodeType` instance.

**Comment by dglazkov** [comment]
There's now an `InspectableNode.type()`, which gives all kinds of fun information about the node type (including the icon).
