### ISSUE TITLE
Adapt the tutorial for the new syntax

### ISSUE THREAD

**Issue by aomarks** [breadboard-ai/breadboard#171]

**Comment by dglazkov** [comment]
Some parts of it are nascent here: 
https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard/docs/fodder/happy-path.md

**Comment by dglazkov** [comment]
For now, let's use the "happy path": https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard/docs/fodder/happy-path.md as a tutorial for new syntax. I am pretty sure we'll end up writing a new tutorial at some point.
