### ISSUE TITLE
Got visual editor into a weird state

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1719]
I can move a shadow of the box, but not the box itself. The wires redraw to the shadow (or maybe a bit offset, too?)

![image](https://github.com/breadboard-ai/breadboard/assets/1934/2ff63110-3a26-4c8f-a51d-aa614be77330)

When I try moving another node, it looks like only the wires move:

![image](https://github.com/breadboard-ai/breadboard/assets/1934/65fff532-b9f7-45bd-9367-08630533633a)

Seems to be new since the pixi.js 8?

**Comment by dglazkov** [comment]
There are no messages in the console

**Comment by paullewis** [comment]
It's to do with the new `isRenderGroup` flag in Pixi. I've switched it off the problematic case.
