### ISSUE TITLE
[UX] Update LLM_content input to solve some core usability problems

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1737]
The LLM_content input type is fast becoming one of the most useful input types, but there are some usability bugs we can address:
1. [x] The description truncation is problem since helper text is hidden. **Solution:** put this on it's own line.
2. [x] The tools on the far right are a little less discoverable. **Solution:** Slight treatment change and left align them to the editor space.
3. [x] The mimetype is informative but not useful and takes up valuable space especially when the properties panel is narrow. **Solution:** Hide the mimetype but keep the blue edit indicator.
4. [x] The hover states of the chunks in the editor are unclear, causing the hover actions to be distanced from the edit area. **Solution:** Use a Grey hover state for each section to connect it to the hover actions. Eventually we could use a drag to reorder for these chuncks.
5. [x] Editing is challenging because the hover actions cover the text. **Solution:** When the chunk is focused, use a light blue background to show that it's in focus. 
6. [ ] The hover actions cover the text. **Solution:** Move the hover actions up so you can see the text currently obscurred.

The top is the current treatment, the bottom is the updated UX
<img width="799" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/5f9c7206-08b9-4979-b374-bd644c7851e4">

Here are the the states: 1) unfocused, 2) hover, 3) focused
<img width="813" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/ef62fd4e-7a87-415d-982f-ecf46c8566e0">

**Read only**
- [x] Hide the blue bar to the left of the chunk and don't use hover states.
- [x] Additionally: large contexts with lots of user model role turns, take too much space. Here's a treatment to collapse all "turns" for a context array into a single widget. In this case, always focus on the last LLM_content
<img width="865" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/7c7a62da-afa9-40dd-b8ec-01d1963ab19d">

**Comment by paullewis** [comment]
I've bounced two remaining smaller items out from here, and declaring victory! :shipit:
