### ISSUE TITLE
[UX] Move the debug popover outside of the properties panel

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1738]
The debug popover is a keyhole with a lot of useful information. Create a targetable debug window over the right edge of the graph: 

This shows the array of LLM_content objects:
<img width="821" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/d7fa5d5b-2f5d-4bd5-93ec-c4f679d5b2a3">

This would be the view if you just show the current json tree view:
<img width="824" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/5c8cc480-d72e-4877-b11c-81d53b20a717">

**Comment by paullewis** [comment]
@donsbach After our chat yesterday I'm thinking you might want to prod some things around for this debug view?

**Comment by paullewis** [comment]
Declaring victory for now, but can revisit this again if we want to push things further.
