### ISSUE TITLE
Teach BGL to remember collapsed/expanded state

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1753]
Currently, if I build a graph with collapsed nodes, and then try to view it when settings are set to uncollapsed, it looks like this:

![image](https://github.com/breadboard-ai/breadboard/assets/1934/89d82f34-4c3a-4eb0-9d52-ce8aa7719c07)

- [x] Add the "collapsed" boolean to node visual metadata
- [ ] Add the "advanced ports" boolean to graph metadata
- [x] Teach Breadboard Web to store the state there

**Comment by donsbach** [comment]
i was just seeing that when i move between localhost and breadboard-ai.

**Comment by paullewis** [comment]
I wonder if we want to have it remember a few of the settings, like advanced ports vs not.

**Comment by dglazkov** [comment]
> I wonder if we want to have it remember a few of the settings, like advanced ports vs not.

Oh that's a really good idea. Let me add that too.

**Comment by dglazkov** [comment]
This is done, right?

**Comment by paullewis** [comment]
It's done for the expand/collapse state. The showing and hiding of ports needs to be stored in the board metadata still because it operates at that level.

**Comment by paullewis** [comment]
Although we could make it a per-node option?

**Comment by dglazkov** [comment]
🚢
