### ISSUE TITLE
[breadboard-web] Add confirmation modal when reloading page

### ISSUE THREAD

**Issue by alexandraM98** [breadboard-ai/breadboard#1766]
In breadboard-web, if I edit the schema for a node and then try to reload, all progress is lost. I believe it would be useful to have a confirmation modal with a message such as "Reload and reset board?" or "Reloading will reset the current setup. Continue?"

Idea for a possible solution (nothing yet attempted):
This could follow the existing approach used for managing events in the breadboard ui elements (binding listeners). 
For example, on the `bb-editor` element, there could be a property `#onReloadConfirmBound = this.#onReloadConfirm.bind(this)`, then in the function called `#onReloadConfirm`, do something to show a confirmation when reloading, such as:
```ts
window.onbeforeunload = function () {
	return "";
};
```

**Comment by paullewis** [comment]
+1 - fix incoming!
