### ISSUE TITLE
[UX] Rejig overlay controls in LLM Content parts

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1769]
Following up from #1737, with the controls as they are we're finding it obstructs visibility of the underlying text content.

**Comment by donsbach** [comment]
Paul, i think we have a more usable interim state after fixes in #1783. Can we call this done or do we need a solve for the hover icons appearing under the top of the prompt area?

**Comment by paullewis** [comment]
I'm happy to call it done for now, and we can revisit it in the future.
