### ISSUE TITLE
Graduate starter kit into separate kits

### ISSUE THREAD

**Issue by seefeldb** [breadboard-ai/breadboard#177]
Now that we've developed a clearer structure for our kits, we can deprecate the starter kit:

- [x] move `jsonata` to the JSON kit
- [x] move `fetch` to the Core kit
- [x] move `runJavascript` to Core kit
- [x] move `secrets` to Core kit
- [x] move `xmToJson` to JSON kit
- [ ] rename the remainder template kit (it's just `promptTemplate` and `urlTemplate`)
- [ ] update examples
- [ ] update docs and tutorials

**Comment by dglazkov** [comment]
I think it's time.
