### ISSUE TITLE
[Bug] When i open the debugger the Activity log scrolls to the bottom of the panel

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1826]
When i click on the debug in the activity log it open the debug but scrolls me to the bottom of the log losing my place.

[scroll bug.webm](https://github.com/breadboard-ai/breadboard/assets/123408/703ab360-706a-4926-8e2d-e9fc2e89c330)

**Comment by paullewis** [comment]
Missed this bug today; I'll take a look tomorrow. Pretty sure I know what it'll be.

(Please do feel free to assign bugs like to me when you file them, and I can always change it if needed.)

**Comment by donsbach** [comment]
Sounds great. The new debugger popout is a gift, but constantly loosing your scroll state is daunting. 
In addition to this bug, I wonder if we could highlight the Activity row when the hover state is shown:
<img width="868" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/ba7de5b2-b394-4db3-90d5-7e845cdc7a59">

**Comment by paullewis** [comment]
Think I need a bit of an assist from @dglazkov on this one. I've tracked it down to the guard on the Activity Log, and in particular `this.run?.events` looks to be fresh on every render, and that means the Activity Log is re-rendered. Not sure what the right thing is for the guard, but it feels like it needs to represent both "there is a new message in a run" or "a message within a run has changed".

**Comment by dglazkov** [comment]
it's a really weird one. I am pretty sure the identity doesn't change, but I am still spelunking...
