### ISSUE TITLE
[UX] Weights on Icons

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1841]
All of our icons are a little too chunky. Can we set the Weights to 300, and the Optical Size to 20:
style="font-variation-settings: 'FILL' 0, 'wght' 300, 'GRAD' 0, 'opsz' 20;"

Current
<img width="419" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/1f634121-20cf-4f14-869f-f94fecbe1fc5">

**Comment by donsbach** [comment]
In the Filters and Settings of the public site you should be able to adjust both... 
![image](https://github.com/breadboard-ai/breadboard/assets/123408/5674b7c8-65fb-41b0-b0cb-4e750dea1a76)

**Comment by paullewis** [comment]
TIL!
