### ISSUE TITLE
Running out of memory with multimodal content

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1851]
For boards that use lots of images/videos, etc., we start running out of memory, since we store all of our content in memory.

This was always something we left for "future us" to fix. We are now future us.

**Comment by paullewis** [comment]
Is it the Activity Log that's the issue here?

**Comment by dglazkov** [comment]
It's really the fact that we keep accumulating runs and all the stuff that is in the run.

**Comment by paullewis** [comment]
Hmm, okay. I guess we'd have to use sentinel values and only keep one copy of the data in the run(s)?

**Comment by dglazkov** [comment]
or store runs in the IDB, etc.

**Comment by dglazkov** [comment]
Duping into #1956
