### ISSUE TITLE
Undo/redo Improvements

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1859]
This bug is to track various improvements that fall out of introducing undo/redo functionality to Visual Editor and Editor API:

- [x] When the user is in various input fields, we shouldn't trigger Editor API undo/redo.
- [x] New nodes are added without coordinates, so undo/redo places them randomly

**Comment by paullewis** [comment]
I have an idea for the second one if you want?

**Comment by dglazkov** [comment]
of course!

**Comment by paullewis** [comment]
The first one is a bit gnarly unless we add something to the Editor API which doesn't create a new version? Or we denounce and only send events when we think user input has "settled".

**Comment by dglazkov** [comment]
> The first one is a bit gnarly unless we add something to the Editor API which doesn't create a new version? Or we denounce and only send events when we think user input has "settled".

I already have a provision for that. Basically, every edit comes with a string label, and behind the scenes, I group all consequent edits with the same label as one history entry, which seems to work pretty well!

**Comment by dglazkov** [comment]
the only problem we have now is that when the user hits Ctrl+Z in the text field, we compete with the text editor.
