### ISSUE TITLE
[Bug] Node Titles have disappeared

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1870]
Help!! Boards that yesterday had Node titles are missing them. Might check if this bug affects Node descriptions as well.

![image](https://github.com/breadboard-ai/breadboard/assets/123408/a98878c7-9f2a-4e42-bfbc-71b2194482b4)

**Comment by paullewis** [comment]
Are the names and descriptions in the JSON at all?

**Comment by dglazkov** [comment]
Yup, I see it too on tip of trunk. To test load "Specialist Testing Grounds". Observe no titles.

**Comment by dglazkov** [comment]
They are still there if I "Undo" -- it looks like they are wiped out by the multi-layout. Let me check in a few...
