### ISSUE TITLE
[Bug] Keyboard shortcuts should be scoped to unfocused controls

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1874]
There are two new keyboard shortcuts that have been added. "h" will toggle history on and off. Command+A with select all. This is great, but we should toggle history with a Command and we should probably not listen to keyboard shortcuts on the Graph when my focus is on an input field somewhere in the UI.

(This bug demonstrates the problem... turn sound on to hear the description)

[Bug Select all.webm](https://github.com/breadboard-ai/breadboard/assets/123408/7878b720-1e74-4356-a7d2-1d11e27ea50f)

**Comment by paullewis** [comment]
I have an immediate fix for this, but when I've got the overflow menu in the top right corner up and running I'll remove the keyboard shortcut 👍🏻
