### ISSUE TITLE
Suggestions for README

### ISSUE THREAD

**Issue by sorvell** [breadboard-ai/breadboard#189]
Here are a few initial impressions and questions from trying to grok what this project is about based on reading the README. 

* Where is this project going? Is there a roadmap? 
* How does this fit with Google's other AI related efforts and tools?
* Other tools like this often have a web-based composer. Is something like that planned?
* How does this compare to what is available from others in this space (e.g. Microsoft, OpenAI, hugging-face, etc.)?

**Comment by sorvell** [comment]
One more quick thought...  As a dev, I want generally to understand what some helper / tool / API /  abstractions are providing me v. doing things myself. When we introduce _AI as the helper_ things can often be magically simple, but it can be a black box of confusion when things go wrong.

There is maybe a spectrum between (START) I do everything myself and (END) the AI tool does everything magically via some multi-modal input (text and images), e.g. "Hey Google, make an app for my friend to use my smart house for the next hour but don't let them lock me out!"

Obviously that end point doesn't exist... yet, but this project is definitely boosting me from that starting point. It seems like it'd be interesting and helpful for understanding to describe milestones between these points and how the various abstractions and APIs here fit into this and provide off ramps. For example, there's:

* the kits here that help abstract over raw LLM APIs
* breadboard graphs (node, wiring API)
* declarative (JSON) representation of graphs
* visual representation of graphs (the mermaid stuff)
* interacting with graphs (playground)
* visually constructing graphs (future playground?)
* ui generation for interacting with graphs (future playground?)
* constructing graphs using AI prompts  (future future playground?)

**Comment by dglazkov** [comment]
Related: #146.

**Comment by dglazkov** [comment]
Folding into #908.
