### ISSUE TITLE
[Bug] On load, first node property panel details are missing

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1893]
I noticed that when a new board is loaded that if you immediately click on a node, the property panel details are missing. If you click on the second node it shows details and the original node will display properly if you click on it again. On refresh, the problem is there on whichever node you click on first. While minor it, it's a little disorienting.

[On load first node is missing details..webm](https://github.com/breadboard-ai/breadboard/assets/123408/31ae8482-f2b9-493f-93a4-84e9dfe27c06)

**Comment by paullewis** [comment]
I am unable to repro this one. @dglazkov, are you able to?

**Comment by paullewis** [comment]
Oh no wait, I can repro... I'll have a look.

**Comment by paullewis** [comment]
Should be fixed.
