### ISSUE TITLE
Visual Editor JS editor sometimes does not save changes 

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1898]
I can't quite produce a repro yet, but it seems like it occasionally gets into a funky state: after accepting edits correctly for a little while, it starts to just ignore them. The current workaround is to go to the next field ("name") and edit it. Then the changes in the JS editor start saving again.

**Comment by paullewis** [comment]
That's really unusual 🤔 The only thing I can think of (which may not be right) is if there's something invalid entered and the state isn't properly cleared that allows it to submit again. But I'm not sure if there's anything to that idea.

**Comment by paullewis** [comment]
Has it happened in multiple fields, or is it always the same field (like LLM input)?

**Comment by dglazkov** [comment]
it's only the JS editor (codemirror) field that seems to do that.

**Comment by paullewis** [comment]
Ah, I misunderstood, I thought it was that we weren't taking updates generally. Okay, I'll have a prod and a ponder.

**Comment by paullewis** [comment]
Okay, so it looks like CodeMirror swallows input events in some cases, so I've added a watcher to the editor for when stuff is removed. Can you see if this is better behaved now?

**Comment by dglazkov** [comment]
🤞🏻

**Comment by PaulKinlan** [comment]
Also - https://github.com/breadboard-ai/breadboard/issues/1929

I will add, it's not just `code`, in my issue `raw` doesn't save either.

**Comment by paullewis** [comment]
This is working now, I believe. Let me know if not, but for now I'll declare victory.
