### ISSUE TITLE
`property-1` on input and `runJavascript` and unable to change the id

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1923]
https://github.com/breadboard-ai/breadboard/assets/45510/6d44a1a7-146b-4820-bcf8-626ed154d691

If I add a new input to the board, and then add a new port and name it title and then I add a runJavascript and connect it to the * port it comes out as `property-1` with no way to change the name in the UI. It's pretty inconvenient to use this in the code in `runJavaScript`.

1) I'd expect it to be the same name as the connecting port.
2) I'd expect to be able to change it.

**Comment by dglazkov** [comment]
Use the new ad hoc wiring hotness! Instead of dragging it into the "*" wire, just drag it onto runJavascript node, wait for it to light up orange, and drop -- it will ask you to name the output.

**Comment by dglazkov** [comment]
Another reason to bump #1849 in priority.

**Comment by paullewis** [comment]
I'm not sure I know what it should be by default, but I'd be happy to pre-fill the input. Do you have any suggestions?

**Comment by PaulKinlan** [comment]
Same name as the origin port?

**Comment by paullewis** [comment]
Okay, I can do that

**Comment by paullewis** [comment]
Fixed in 85f023d751977318424b794bef5b009204923d84, with an additional boost from #1989
