### ISSUE TITLE
Teach Activity log input to enter LLM Content arrays

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1928]
<img width="1167" alt="Screenshot 2024-05-23 at 10 50 36" src="https://github.com/breadboard-ai/breadboard/assets/45510/63c01cbd-7777-462d-ac65-370492bffe63">

It errors with `Uncaught TypeError: a.map is not a function`

Board attached.

[board-2024-05-23T09_50_20.401Z.json](https://github.com/breadboard-ai/breadboard/files/15415023/board-2024-05-23T09_50_20.401Z.json)

I'll be honest, I'm not sure if I should be passing in `LLM Content` but all the other tools do.

**Comment by dglazkov** [comment]
The input can now handle LLM Content Arrays!
