### ISSUE TITLE
runJavaScript code not updating even after saving

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1929]
https://github.com/breadboard-ai/breadboard/assets/45510/198b74b9-720d-435d-bff6-2452962d93a4

It just keeps reverting

**Comment by PaulKinlan** [comment]
Note the same happens if I try and set `Raw`

**Comment by paullewis** [comment]
Should be fixed in the latest deploy. Can you try again?

**Comment by paullewis** [comment]
I think this one is now fixed, but lmk if not.
