### ISSUE TITLE
Allow `runJavaScript` to have named ports

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1930]
<img width="1257" alt="Screenshot 2024-05-23 at 11 01 27" src="https://github.com/breadboard-ai/breadboard/assets/45510/c17dfb52-1681-4bdd-af2c-1c3c043ae332">

It's confusing that I can't create a named port on `runJavaScript` when setting it to `raw: true`. It also means that I have to attach `*->*` on the destination of the edge. In this case I really need both to go to `Context`

**Comment by dglazkov** [comment]
This seems like a bug in runJavascript describer.

**Comment by dglazkov** [comment]
Would you be up for fixing it?

**Comment by PaulKinlan** [comment]
I can have a look. Thinking on it, I suspect that some of the issue might be because the code as to run to get the response... will have a noodle.

**Comment by PaulKinlan** [comment]
Actually, I can see some differences as it was moved over to the new type system. Will catch up with @aomarks today

**Comment by aomarks** [comment]
Ah yeah, I was thinking about this when doing the conversion. I think we should have a `schema` port for this.

The new `code` helper now has schema for input and output types, we currently only use it for TypeScript type checking, but we could also send that into a `schema` port, and then make the `describe` function reflect those provided schemas (similar to how input/output take schemas).

**Comment by aomarks** [comment]
> runJavaScriptSchema.mp4 
> Preview of it working.

Awesome!
