### ISSUE TITLE
Can't drag a wire to an output node and get it to automatically create a named port

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1931]
https://github.com/breadboard-ai/breadboard/assets/45510/dc136ef3-983b-451e-b476-ef2873c0a867

I'd like to be able to drag a wire from a port on to an output node and get it to give me the ability to name the output

**Comment by paullewis** [comment]
Right, the ports on an output are fixed and only editable via its schema. Changing that would either mean automatically adding a property to the schema or unfixing the outputs, and I'm not sure if either of those is ideal. @dglazkov wdyt?

**Comment by paullewis** [comment]
Going to mark as WAI. Happy to revisit in the future though!
