### ISSUE TITLE
Bring back the property id in `port-spec` schema editor

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1953]
In some situations (like when the board is invoked as a function), it is important to be able to set the property id. Current workaround:

1. create a node
2. copy and paste node into a text editor
3. change the property name
4. copy and paste BGL back into the visual editor.

**Comment by paullewis** [comment]
This should be what you want, because I mostly switched out the old input[type="text"] for input[type="hidden"], so all the "I renamed a property" logic was still intact. Can you double check it when you get a mo? For now, though, I'll declare victory!

**Comment by dglazkov** [comment]
perfect! Can we move it under "show more"?

**Comment by paullewis** [comment]
Done
