### ISSUE TITLE
Web App UX: Inputs lost if list is long, need scroll area controls

### ISSUE THREAD

**Issue by zeroasterisk** [breadboard-ai/breadboard#196]
## Expected Behavior

Loading a board, you should be able to enter inputs without getting lost.  

It's the 2nd action you want a user to take, after looking at the graph.

## Actual Behavior

The inputs area requires a "scroll to top" to see the `text` input, but that's not at all obvious for new users of the UX.

<img width="1053" alt="2023-12-15_11-38-46" src="https://github.com/breadboard-ai/breadboard/assets/23422/9045a694-ee5e-4455-b536-698a692a3fea">

## Steps to Reproduce the Problem

1. Load any board in the webapp, with many inputs, but not a large vertical area

## Specifications

- Board Caller / Version 0.0.6
https://breadboard-ai.web.app/?board=%2Fgraphs%2Fboard-caller.json

## Recommendation

1. easy: I tried to do something like `#history, #output, #input { overflow: auto; }` but I couldn't get it to work.  
2. hard: Consider a more dynamic interface which responds to the complexity of the board's data, and the screen size... perhaps splitting into tabs instead of stacks, or an accordion type of expand-collapse interface.

**Comment by dglazkov** [comment]
Yup, also found this in #427.

**Comment by dglazkov** [comment]
@paullewis, I wonder if the solution is to have a designated "Continue/Run" button in the UI? Would love to figure this out for M4.

**Comment by paullewis** [comment]
Yes it's on my list, ideally for this week!
