### ISSUE TITLE
Convert README to Build API syntax

### ISSUE THREAD

**Issue by TinaNikou** [breadboard-ai/breadboard#1994]
Convert the README doc (`./packages/breadboard/README.md`) to the [Build API](https://github.com/breadboard-ai/breadboard/tree/main/packages/build) syntax.

**Comment by TinaNikou** [comment]
@dglazkov Hi Dimitri! This file has since been deleted from the repo, and I was wondering if you would still want it converted to the Build API or if this issue should be closed now? Thank you :heart_hands:

**Comment by dglazkov** [comment]
Ready to close!
