### ISSUE TITLE
[Bug] Edges missing from back stack

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#2006]
If I command undo after deleting my graph, the nodes return but they're missing the edges.

(video has audio)
[Edges missing from back stack.webm](https://github.com/breadboard-ai/breadboard/assets/123408/4f9be428-0c99-479a-b35e-d24c7f2c540b)

**Comment by paullewis** [comment]
Yeah, this is because I added the multi-delete feature before we supported undo/redo. It turns out they're there, they're just earlier in the undo stack. I will update this code to use the multi-edit feature so they come and go as a single operation 👍🏻
