### ISSUE TITLE
[Bug] When you change the schema you get some weird default text

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#2008]
Create an input that's an LLM_content element. Run the board and provide a value for this field. Now change the field to a string. You'll see it still tries to populated the LLM_content in the string field. We should probably clear the default values when the input type changes.

<img width="357" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/3b055e6f-4a79-4761-b9c7-718251e82de9">

**Comment by paullewis** [comment]
Fixed in cf7710cdc238755004194818d5c64c7cebbe9c47 - we now remove the default & format values when switching out from LLM Content to anything else.
