### ISSUE TITLE
[Bug] Human presents option picker with 1 option

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#2011]
When I have a Human and a Specialist in a chat loop, if the Specialist calls a tool (even once) the User has to pick an option or it skips the user all together. I think we need to 1) only present options when the user has multiple tool calls, 2) make sure we don't inherit the option selection from previous turns, 3) don't skip the user input.

(video has audio)

[Bug with a human in a chat loop with a tool calling specialist.webm](https://github.com/breadboard-ai/breadboard/assets/123408/7bad9a43-ab6a-44bb-9a59-3f9004cf5a09)

**Comment by dglazkov** [comment]
Ooh that's a good one.

**Comment by donsbach** [comment]
[board-2024-05-31T19_58_21.934Z.json](https://github.com/user-attachments/files/15518220/board-2024-05-31T19_58_21.934Z.json)
