### ISSUE TITLE
[FR] Update blank to LLM Content instead of string?

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2015]
When we create a new board we have input.text -> output.text, and both ports are strings. It seems the first move we tend to make is to convert from string to Object => LLM Content. What if we update the blank.ts to use the following for its configuration:

```
{
    schema: {
      properties: {
        content: {
          type: "object",
          title: "Content",
          examples: [],
          behavior: ["llm-content"],
          default:
            type === "input" ? '{"role":"user","parts":[{"text":""}]}' : "null",
        },
      },
      type: "object",
      required: [],
    },
  }
```

Or we could make a second blank-llm.ts template?

**Comment by dglazkov** [comment]
I really like this idea. Let's do this.
