### ISSUE TITLE
[FR]: Allow clicking on the parts input to directly create a text part

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#2089]
for user-friendliness, it'd be very nice if clicking into an unpopulated  ``bb-llm-input` created a text part so you could just start typing.
![CleanShot 2024-06-11 at 09 56 25](https://github.com/breadboard-ai/breadboard/assets/1331872/33ab80ea-509f-4510-9dcc-4af7671a3211)

**Comment by paullewis** [comment]
I really like this idea. We've gone back and forth on it a few times because the `default` block is where we normally need to create any placeholder type inputs. But your suggestion is great because it augments that.
