### ISSUE TITLE
[Bug] Hide Advance ports should still show a port if it's connected

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#2148]
This behavior is unexpected. In this case the promptTemplate feeds into the Task, but when the "Hide advanced ports" is selected it loses visibility to the connection between the two nodes.

[Hide advanced port bug.webm](https://github.com/breadboard-ai/breadboard/assets/123408/41bea32e-66ab-49b0-ab61-99a2dd5fd964)

**Comment by paullewis** [comment]
I'm unable to reproduce this one.

<img width="533" alt="Screenshot 2024-06-17 at 14 39 36" src="https://github.com/breadboard-ai/breadboard/assets/617438/b91fe32e-cc68-4c0e-90a0-08c1115160c1">

Looking at the filter function it does leave intact any connected, dangling or configured ports in place. Would you be able to send me the board that's misbehaving and I'll see if I can find out what's different?

**Comment by paullewis** [comment]
Fixed
