### ISSUE TITLE
[FR] Board server listing to include "mine" property?

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2186]
RE: #2184, we don't currently tie the username in the board listings to anything held locally. Locally we have the API key, and remotely we present a board as @username/board.json. This means it's tricky to know if you're the owner of a board or not.

Options that I can think of:

1. Store a username locally (seems unnecessary)
2. Return an optional `"mine": boolean` property in the board listing
3. Infer from the `readonly` property that you're the owner

FWIW I feel like 2 is the least worst of those options, because 1 feels superfluous, and 3 doesn't feel like it would hold for a more lenient board server. wdyt?

**Comment by paullewis** [comment]
And FWIW I can see it being a separate flag to readonly because I could imagine cases where you might want to "lock" a board, even though you own it, to prevent accidental overwrites. Kinda like the little tab you pulled out of a VHS tape to stop it being recorded over, or the slidable tab on an SD card.

**Comment by paullewis** [comment]
If we're changing this around, could we also include the board title? I think there might be an option to use the board title & URL in the left nav in a more compelling way. I can get most of that information quite easily from the other providers, but the RemoteGraphProvider would have to ping all boards individually to get their titles, and I think it might be handy if the listing included it. wdyt?

**Comment by dglazkov** [comment]
There are now `title` and `mine` properties being sent with the board list, along with the existing `path` and `readonly`.

Also, there's now a `published` tag that you can set on the board (in `GraphMetadata.tags`). If the tag is present, the board will appear in the list for everyone. If the tag is not present, it will only show up for you.

**Comment by dglazkov** [comment]
I also added this bit for now:

https://github.com/breadboard-ai/breadboard/blob/7c1b4cbb4dcf27e9a79255356c7e93d2d2fd8600/packages/breadboard-web/src/providers/remote.ts#L251

Once the published/unpublished UI is working, we need to not forget to remove the "published" by default flag

**Comment by paullewis** [comment]
As of https://github.com/breadboard-ai/breadboard/pull/2221 we should be good to go.

**Comment by paullewis** [comment]
Would it be possible to add `"published": boolean` to the board listing when `"mine"` is set? We always list someone's boards, but I think having something in the listing that quickly indicates to them whether or not the board is public would be really helpful.

**Comment by paullewis** [comment]
Actually let me make a new bug for that...
