### ISSUE TITLE
Clean up old examples in Example Provider

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2192]
There are a lot of examples in the Example Provider that feel a little stale now we have more advanced kits. We should probably consolidate our newer examples and such so that they feel geared towards particular use-cases.

**Comment by paullewis** [comment]
Thining we should migrate `packages/boards` to providing the examples for the Examples Provider in the Visual Editor.

**Comment by Mearman** [comment]
still WIP https://exadev.github.io/projects/Breadboard/Boards

**Comment by paullewis** [comment]
Fixed by virtue of making a Playground / Examples split
