### ISSUE TITLE
Update Getting Started doc code to produce expected outputs

### ISSUE THREAD

**Issue by itsjorgebar** [breadboard-ai/breadboard#2198]
## Expected Behavior
The commands in [Getting Started 
](https://breadboard-ai.github.io/breadboard/docs/getting-started/#run-your-first-board) should output `{ "hear": "Hello World!" }` as shown in the doc.

## Actual Behavior
1. [Run your fist board](https://breadboard-ai.github.io/breadboard/docs/getting-started/#run-your-first-board) outputs only warnings:

> (node:43383) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)

2. The doc is missing the instruction to add `"type": "module"` to `package.json` to avoid the error:

> /Users/jorgebar/my-breadboard/hello.js:1
> import { base, board } from "@google-labs/breadboard";
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module

3. [Generating boards with JavaScript](https://breadboard-ai.github.io/breadboard/docs/getting-started/#run-your-first-board) outputs empty object:

> (node:43457) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> {}

 

## Specifications
- Version: Node.js v20.14.0

**Comment by dglazkov** [comment]
I wonder if we're better off just deleting this guide. It's code-rotted quite a bit. Maybe a fresh start focusing on Visual Editor, WDYT?

**Comment by itsjorgebar** [comment]
Let's do it! (Created #2213)
