### ISSUE TITLE
Create board manifest specification

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#2215]
- see: https://github.com/breadboard-ai/breadboard/issues/2152

**Comment by Mearman** [comment]
In the boards array, currently it's references to locations of boards.
Is the consensus that allowing full board definitions in there would be a bad idea?
It's a tempting idea, but probably not a good one, purely because of how bulky the file would get.

**Comment by dglazkov** [comment]
> Is the consensus that allowing full board definitions in there would be a bad idea?

From the packaging/bundling perspective, I think we should allow it. Let peeps roll up entire bundles of boards into one.

Also, this manifest format needs to be the format we use for Kits. Currently, it's a simple manifest format that I threw together quickly:

https://github.com/breadboard-ai/breadboard/blob/da4bc22ad7449bf5e0cecfd1ead3d4701a65bdeb/packages/agent-kit/agent.kit.json

https://github.com/breadboard-ai/breadboard/blob/da4bc22ad7449bf5e0cecfd1ead3d4701a65bdeb/packages/agent-kit/src/generate-kit-manifest.ts

Let's make them one and the same.

This way, the way to distribute kits is to supply a manifest of boards.
