### ISSUE TITLE
[FR] Add "published" to board listing when "mine" is true.

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2222]
Would it be possible to add `"published": boolean` to the board listing when `"mine"` is set? We always list someone's boards, but I think having something in the listing that quickly indicates to them whether or not the board is public would be really helpful. 

The overlay card that we plan to show in the provider UI would likely need it, too, now I think on it.

**Comment by paullewis** [comment]
Or better yet, just show the tags. Then we know whether a board is a tool.

**Comment by paullewis** [comment]
And can we add the `"username"`, too?

**Comment by dglazkov** [comment]
Yes! The board server will now send title, username, and tags along with the other bits:

```ts
export type BoardListEntry = {
  title: string;
  path: string;
  username: string;
  readonly: boolean;
  mine: boolean;
  tags: string[];
};
```
