### ISSUE TITLE
[FR] Board server should allow dry run saves?

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2231]
I'm adding the "Save as" functionality, which means it's possible to create a file naming clash. For file system and IDB this is solvable by querying the provider itself, but for Board Servers it's possible that the listing is out of date. I'm wondering if we should have something that allows us to do a check if there's a file already in existence?

It may not be the right approach, but the thought I had was that the save call could add a "dry-run" flag somewhere, which fails if the file already exists, but also doesn't create the file. That way when the user enters the file name I can query the provider to ask if the file exists already.

**Comment by dglazkov** [comment]
yes! I have something like that here:

https://github.com/breadboard-ai/breadboard/blob/54b03b956bd319c031b4eeb15260e40f19e53895/packages/breadboard-web/src/providers/remote.ts#L131-L134

I need to teach it to check for duplicates.

**Comment by dglazkov** [comment]
So when #2283 lands, it will do a couple of things:

by default, when you make a POST request from above, it will find the unique name and create blank board and give the found name back to you. This way, you always get the unique name on the board server.

If you also supply `"dryRun": true` as a property, it will do all of the above except creating a blank board.
