### ISSUE TITLE
Pasting Board JSON results in all nodes being stacked on top of each other

### ISSUE THREAD

**Issue by kex103** [breadboard-ai/breadboard#2255]
## Expected Behavior
The nodes should be spread out a bit so that they can be seen.

## Actual Behavior
When pasting board JSON into the board editor, all nodes end up being stacked on top of each other, so that only one node is visible.

## Steps to Reproduce the Problem

1. Copy board JSON from a text file.
2. Paste on board editor
<img width="776" alt="Screenshot 2024-06-21 at 2 47 11 PM" src="https://github.com/breadboard-ai/breadboard/assets/3093240/67ba8860-d80d-4154-9949-ee34545ff19e">

## Specifications

- Version:
- Platform:

**Comment by paullewis** [comment]
Interesting. This will depend somewhat on the nature of the thing being pasted. Do you have an example file I can try?
