### ISSUE TITLE
Make OOBE experience more friendly

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2265]

**Comment by dglazkov** [comment]
What can we do to make out of the box (OOBE) experience more friendly? A couple of ideas:

- when first run, BB lands the user on the tutorial board, which helps them orient (what the heck is this? What's it for? What do I do next?)
- The tutorial board points at examples in the left sidebar maybe?
- The examples contain links to guides?
- Somehow, when I start next time, I can choose to start with a blank board or ... maybe last board I edited?

**Comment by paullewis** [comment]
Declaring victory on this one – I think the other bugs in #1818 have a few bits that will improve this story, too.
