### ISSUE TITLE
Freshen up the project directory structure

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2271]
Remove these:
- [x] coffee-bot-board
- [x] graph-integrity
- [x] graph-playground
- [x] graph-runner
- [x] llm-starter
- [x] node-nursery
- [x] pinecone-kit
- [x] team-kit

Consider removing these or moving them to `./archive`:

- [x] cloud-function
- [x] breadboard-extension
- [x] breadboard-server
- [x] breadbuddy
- [x] create-breadboard
- [x] create-breadboard-kit

**Comment by dglazkov** [comment]
@paullewis  shall we keep breadbuddy?

**Comment by paullewis** [comment]
We could repurpose it for a Chrome Extension? But if we aren't going to do that then let's get rid.

**Comment by paullewis** [comment]
Decided to remove breadbuddy (it will return!) and renamed breadboard-web/-ui to visual-editor

**Comment by paullewis** [comment]
Will archive the last few and declare victory
