### ISSUE TITLE
Breadboard recipe gallery

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#233]
Let's build a thing that allows standing up a public or private gallery of recipes, with an easy way to contribute recipes to it.

A scaffolding for a simplest-possible service that could be hosted publicly and privately. We will likely host one for all the cool recipes we've made.

Also, any team should be able to just stand up their own private gallery where they can safely exchange recipes amongst themselves.

**Comment by PaulKinlan** [comment]
I imagine that we could spin this up as an 11ty service, like what @aomarks was talking about with the docs site.

Some thoughts about management (at least to start with), I imagine we could use github to accept recipes. That way they can be reviewed, there might also be meta data from the commits too that we can use.

**Comment by aomarks** [comment]
> Some thoughts about management (at least to start with), I imagine we could use github to accept recipes. That way they can be reviewed, there might also be meta data from the commits too that we can use.

I like this idea! Start really simple. We can set up auto-deployment so that after we merge a PR with a new recipe, it goes live automatically.

**Comment by dglazkov** [comment]
Another advantage of breadboard: it's just JSON files. If someone wanted to federate recipes, it's really just a matter of pointing to a JSON file, like this one: https://raw.githubusercontent.com/breadboard-ai/breadboard/main/packages/breadboard-web/public/local-boards.json

**Comment by dglazkov** [comment]
We might want to elevate `local-boards.json` to its own concepts, like a manifest file.

**Comment by dglazkov** [comment]
Duping this against #1853
