### ISSUE TITLE
Specialist can't call embedded sub boards

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2393]
If a Specialist is given an embedded sub board as a tool it can't run it. If the same board is somehow external then it seems to work just fine.

Failing board attached.
[Subboard-tool.json](https://github.com/user-attachments/files/16071670/Subboard-tool.json)

**Comment by dglazkov** [comment]
Ooh, I know this one. I bet the `curry` node doesn't support sub-boards.

**Comment by dglazkov** [comment]
Ooh, I know this one. I bet the `curry` node doesn't support sub-boards.

**Comment by dglazkov** [comment]
This is a tough one. It's a loader bug. Basically, I have no way of knowing what the relative URL (the `#<board-id-guid>`) is relative to at runtime. I thought I fixed it, but clearly not.
