### ISSUE TITLE
[visual-editor] Every alternate build of VE removes agent.kit.json

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2402]
@aomarks Is there an easy way to use wireit to determine why the file is being removed?

**Comment by paullewis** [comment]
To repro go to the visual editor and `npm run build` and see that `agent.kit.json` is removed. Run it again and it reappears.

**Comment by aomarks** [comment]
> @aomarks Is there an easy way to use wireit to determine why the file is being removed?

Not right now. Would be great to add a detailed debugging log output to wireit for cases like this.

> To repro go to the visual editor and `npm run build` and see that `agent.kit.json` is removed. Run it again and it reappears.

I think I've seen this before as well, though it doesn't repro for me right now for whatever reason. In any case, I suspect https://github.com/breadboard-ai/breadboard/pull/2403 could be the fix (from a mistake I made with the recent pyodide python support), please let me know either way @paullewis!
