### ISSUE TITLE
Constant text field problems on Linux Chrome

### ISSUE THREAD

**Issue by dcblack-google** [breadboard-ai/breadboard#2412]
When accessing Breadboard via Chrome on Linux, I'm constantly finding myself unable to edit text fields and needing to refresh the page, and occasionally edits I make in text fields don't stick.  Very frustrating, and has happened to me perhaps around a dozen times today.

**Comment by paullewis** [comment]
I have a hunch that this is down to the Code Editor locking out focus again. I'll see if I can make it more robust – sorry for the frustration!
