### ISSUE TITLE
pretty URLs

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#2443]
as all modern browsers handle encoding URLs, on board load, push the decoded URL so it looks pretty
demo in browser console
```javascript
const currentUrl = new URL(window.location.href);
const decodedUrl = decodeURIComponent(currentUrl.href);
window.history.replaceState({ path: decodedUrl }, '', decodedUrl);
```

ooooh pretty URL
![CleanShot 2024-07-08 at 10 53 34](https://github.com/breadboard-ai/breadboard/assets/1331872/3835cf3f-2e46-4e5c-87a6-41710e4897d1)

**Comment by alexandraM98** [comment]
Addressed this issue [here](https://github.com/ExaDev/breadboard/tree/2443-use-pretty-urls)

Here's a preview:
https://github.com/user-attachments/assets/7c10718b-6e8d-4919-9abb-932fab643f93
