### ISSUE TITLE
[Visual Editor / Storage] Images seem to disappear from inputs on 3rd run

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#2528]
1. Start with a blank board.
2. Run the board and choose an image, click continue.
3. Run the board a second time, click continue.
4. Run the board a magical third time, and the image will be missing – I suspect it's something to do with the storage.

<img width="414" alt="Screenshot 2024-07-15 at 20 06 30" src="https://github.com/user-attachments/assets/42fb4e81-384c-4bf8-9fa4-8f9f272563bc">

@dglazkov if you have time to look, yay. If not, I'll take a look tomorrow!

**Comment by dglazkov** [comment]
oh yeah. This is because the run observer only keeps two last runs around (and purges the storage for the rest). I suspect we need a dance of moving these somehow up to the current run, so that they are always kept.

**Comment by paullewis** [comment]
A somewhat related issue is that if we set an input to be – say – a POJO and do a run where we enter something like `{"x": 100}` and then we change the input to have a behavior of `board` then it will switch the item, but we will reuse the previous run value to try and populate the new input. I can add stuff to the UI because it should be robust in these cases, but I also wonder if we want some form of "this input has changed so maybe check if the value is still valid" handling?
