### ISSUE TITLE
Board embeds need one more refresh for boards with curry/invoke/map components

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2552]
When looking over https://breadboard-ai.github.io/breadboard/docs/kits/core/, the example boards for curry, map, and invoke have red dots and ports look like they haven't been described correctly.

In embedded view:

![image](https://github.com/user-attachments/assets/90c3bdc4-5e64-414a-a635-bf0f1fc57da0)

In VE:

![image](https://github.com/user-attachments/assets/91aa3058-7923-49c2-87a3-716aa8ad9691)

Is this because we stop rendering the board without waiting on all describers to load? I haven't looked in depth.

**Comment by dglazkov** [comment]
@paullewis forgot to add you!

**Comment by paullewis** [comment]
Hmm, not sure. I thought I was awaiting all kits before loading the board 🤔

**Comment by dglazkov** [comment]
There's one more moment -- once all kits are loaded, the shape of invoke/map/reduce/curry changes when they load their board as argument.

**Comment by paullewis** [comment]
Oh interesting. Where do we currently do that work?

**Comment by dglazkov** [comment]
Let me spelunk real quick. It should be somewhere in how we call describe

**Comment by dglazkov** [comment]
It was me. 😝

**Comment by dglazkov** [comment]
What happened here is that I used to rely on `NodeHandlerContext.base` for loading, and transplanted that code to describer methods. However, describers don't actually use `base` at all, and they were bailing early in the `context.base` check.

**Comment by dglazkov** [comment]
Wait, no.. I got this backward. the problem is that the `GraphDescriptor` supplied to to the `bb-editor` in the `bb-board-embed` didn't have the graph URL assigned.
