### ISSUE TITLE
Board picker shows "No Board" when a board is selected

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2584]
Despite the actual board being selected, the board picker might not show anything.

![image](https://github.com/user-attachments/assets/c3fef5e3-9d81-408f-9cbd-a536c2033b69)

This likely happens because we are filtering non-tool boards, and when a board selected isn't a tool (from before when we allowed that), it defaults to empty.

My guess is that we need to have a bit more nuance here somehow? Maybe allow showing non-tool boards? I don't know.

@billbyrne who found it.

**Comment by paullewis** [comment]
Huh that might be a bug. It should show it as a custom URL.

**Comment by paullewis** [comment]
If there's a particular board where it does it, let me know. If not I'll try and repro on Monday.

**Comment by dglazkov** [comment]
sent you a chat

**Comment by paullewis** [comment]
This ended up being a fun one. I needed to check that the board has a `'tool'` tag before being accepted as a board from the list (rather than a custom URL). If it didn't we'd expect it to be in the list, but the list has non-tool boards excluded ergo "no board".
