### ISSUE TITLE
Code editor disappears after a little bit

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2586]
Not quite sure what is happening, but working with the new unified controls, the code editor is more shy than usual. After working just fine for a few board runs, it just kind of disappears:

![image](https://github.com/user-attachments/assets/9bbc3ef4-514b-4d3e-aa20-7474ad800a55)

The workaround is to save and reload the editor.

**Comment by paullewis** [comment]
In the dance to stop CodeMirror keeping focus I suspect we are bit too keen to destroy its instance. The short term workaround is to go to another component and back again, and it should appear. For whatever reason (which I guess is the cause of this bug) going from the board side panel to the component one seems to cause this 🤔
