### ISSUE TITLE
Teach board runs to be interruptible

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2674]
Primary use case is the `/run` API endpoint, where the board runs on the server and is able to stop/restart whenever user input (or output) is needed.

- [x] Support simple interruptible run (input in the middle of a board)
- [x] Support nested boards (invoke)
- [x] Support map and reduce
- [x] Connect `/run` API endpoint
- [x] Teach the Board server to save/load state and vend tickets
- [x] Document the API

**Comment by dglazkov** [comment]
Declaring victory 🚢

**Comment by Mearman** [comment]
is it in a position for me to start poking at it?

**Comment by dglazkov** [comment]
Still very raw, but yes: https://breadboard-ai.github.io/breadboard/docs/reference/board-run-api-endpoint/
