### ISSUE TITLE
Make Joiner choices more explicit.

### ISSUE THREAD

**Issue by itsjorgebar** [breadboard-ai/breadboard#2706]
## Expected Behavior
Choices used to be displayed in a dropdown.
![image](https://github.com/user-attachments/assets/27195f5c-2d9a-45d8-8211-14b94c857309)

## Actual Behavior
Choices are now typed into a textbox. The options are not displayed, which makes it hard to figure out what to type.
![image](https://github.com/user-attachments/assets/899c5e8d-fa0e-4e18-a2aa-8318a85d154a)

## Steps to Reproduce the Problem

1. Run a board with a Joiner, such as the [Novel Outliner](https://breadboard-ai.github.io/breadboard/docs/guides/novel-generator/)

## Caveat

Two solutions come to mind:
1. Mention that the input format is "Choice 1", "Choice 2", etc.
2. Bring back the dropdown. (The best IMHO, but I suppose it was removed for a reason.)

**Comment by dglazkov** [comment]
@paullewis ohhhh, I think the new controls don't yet support the enums. Is that right?

**Comment by paullewis** [comment]
Yes, oversight on my part. Fix inbound.
