### ISSUE TITLE
Image in input is replaced with the image from previous run

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2725]
[Data Store Bug.webm](https://github.com/user-attachments/assets/5e5c7406-8f21-4b4f-8a0f-0bed0d46782a)

1. Run a blank board with image 1 (Music For the Masses album cover) to completion
2. "Run Board" again
3. As expected, the image 1 will be pre-filled
4. Delete image and upload image 2 (Yellow submarine album cover)
5. The input still shows image 1
6. Click "Continue"
7. The yellow image 2 cover shows up as both input and output.

@paullewis  I am guessing this is because of the data store refactor. Will spelunk this weekend if I have time.

**Comment by paullewis** [comment]
Well I can repro... let's see if I can find out why it's happening.
