### ISSUE TITLE
`runJavaScript` to `core-kit`?

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#273]
When using the new syntax `code()` and `recipe`, it requires `runJavaScript` and `invoke`, both of which are in different kits.

Should they be in the same kit? 

We don't notice it in things like `breadboard-ui` because we always include them, however on the CLI and any apps I build I now have to make sure I always include them.

**Comment by dglazkov** [comment]
Dupe of #177
