### ISSUE TITLE
Teach board server to stream updates

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2735]
Next step after #2674: let's stream updates as they happen during the segment of a run: nodestart, nodeend, graphstart,graphend, etc.

- [x] #2760
- [x] #2762
- [x] #2813
- [x] #2814
- [x] #2828

**Comment by dglazkov** [comment]
Let's see if we can get this running over websockets

**Comment by dglazkov** [comment]
it sounds like the only path so far (at least for GCP-based deployment target) is using Cloud Run.

**Comment by paullewis** [comment]
Do we want a RemoteRunStore as part of this as well, that way runs on a server can also be sent to a store somewhere else?

**Comment by dglazkov** [comment]
Declaring victory 🚢
