### ISSUE TITLE
Build a single-file, all doc snapshot of website

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#2749]
For easy consumption by an LLM, let's automatically build a giant single file of all markdown on the site.

Would love some help here.

**Comment by wfaithfull** [comment]
Is this what you have in mind @dglazkov 

```
(find . -iname "*.md" -not -path "*/.wireit/*" -not -path "*/node_modules/*" -exec cat {} +) > all_markdown.md
```

**Comment by dglazkov** [comment]
it might work! I was imagining something more elaborate, like using eleventy to concatenate and format the files (remove front matter, etc.) nicely, but your script sounds like a good first step.
