### ISSUE TITLE
Build documentation references ambiguous file with no equivalent obvious

### ISSUE THREAD

**Issue by dans-dev** [breadboard-ai/breadboard#2810]
The current documentation for the Build package references '../build-example-kit.js', which is ambiguous, upon trying to find this file I found one, which did not correspond to the docs, and gave me little in the way of assistance.

**Comment by aomarks** [comment]
Yep, sorry about that, the README docs got a bit stale. Follow https://github.com/breadboard-ai/breadboard/issues/2687 which tracks full docs on our documentation website.
