### ISSUE TITLE
[board-server] If not running in GCP, take secrets from environment variables

### ISSUE THREAD

**Issue by wfaithfull** [breadboard-ai/breadboard#2963]
We are trying to remove external dependencies from the board server to lower the barrier to entry to getting one up and running. One more external dependency that it has is Google Secrets Manager, which requires you practically to run it on GCP. But if we fallback to environment variables, we can run _anywhere_ 🙂 

@dglazkov knows of a way to enable this behaviour.
> heeey, I can make secrets manager be flexible. If it detects a GCP environment, it will opt for Secrets Manager, otherwise, just read from envs

**Comment by dglazkov** [comment]
Would a `secrets.json` file work? I need to store key origin URLs alongside with the values.

**Comment by dglazkov** [comment]
alternatively,  could do something like:

```sh
KEY="{"value": "value", "origin": "origin" }"
```
