### ISSUE TITLE
[breadboard] BoardRunner.load() or `getRunnableBoard` in core/invoke should resolve the path.

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#298]
When trying to invoke a board with a relative file path i.e, `core.invoke({path:'./some-path.json'})`, the path is passed to `BoardRunner.load` as relative path and because `BoardRunner.load` doesn't resolve the path to an absolute path then `./` will assume the base of the path is `/packages/breadboard/dist/src/` and not the current working directory.

**Comment by PaulKinlan** [comment]
This can be fixed in the `invoke` node with a simple ` path = resolve(process.cwd(), path);`, however it might need to be resolved at a lower level in BoardRunner.

**Comment by dglazkov** [comment]
Try giving it a `base` option:

```js
await runner.load(url, { base: yourBaseURL });
```

**Comment by PaulKinlan** [comment]
Hmm... I'd break the build with my solution as it's not browser friendly.

I'm also having some trouble with overriding the `base`:

I can't used `runner.load` - because I am loading from JSON directly with `Board.fromGraphDescriptor`.

Next, looking through invoke, it accepts a `base` parameter as the context on `run`, however  I think there is a bug in `BoardRunner.run` - when it creates a new context it overrides some of the context with data from the board.

```
 const newContext: NodeHandlerContext = {
          ...context,
          board: this,
          descriptor,
          outerGraph: this.#outerGraph || this,
          base: this.url, // <<<<< HERE...
          slots,
          kits: [...(context.kits || []), ...this.kits],
          requestInput: requestedInputs.createHandler(next, result),
        };
```

See `base` is overriden. My boards don't have a URL supplied (so it becomes undefined).

Next, if I do fix the above issue by moving `...context` to after `base` (which kinda works), it breaks the lambda for which uses `#fn-XXX` because it now has a full file path for the lambda (sub-graph)....

**Comment by dglazkov** [comment]
Ah, this might be working as intended! When we use `fromGraphDescriptor`, we lose the accurate location of the graph -- so we need to supply it again to properly locate it. So, the right thing to do here is to specify the URL:

```js
json.url = "<your url here>";
const graph = Board.fromGraphDescriptor(json);
```

**Comment by dglazkov** [comment]
I also can't remember why we decided to use `fromGraphDescriptor`. The pattern I'd like to encourage is what's here:

https://github.com/breadboard-ai/breadboard/blob/main/packages/graph-playground/src/index.ts#L169

**Comment by PaulKinlan** [comment]
Iirc, we'd discussed on the discord that we shouldn't use `load` and we should use from graph descriptor method - (iirc, we had an error with spaces in the file:// URLs)

**Comment by dglazkov** [comment]
> Iirc, we'd discussed on the discord that we shouldn't use `load` and we should use from graph descriptor method

Yeah, I vaguely remember. Let's see if we can get it right this time. Can we try using `Board.load` once more and troubleshoot if it doesn't work?

**Comment by PaulKinlan** [comment]
Yes, I can look in to it - I've already changed the JSON loader (testing now) which has the base defined.
 
The more complex area, is that I realises now why I am not using `load` for everything, and it makes it a tad more complex... If you `npx breadboard <a JS file>` (not a json file) I will `await import().default` to load the board then use `fromGraphDescriptor` to load the board, most of the files we are importing are `GraphDescriptor` (the result of recipe.serialize).

I want to avoid using temporary files (but I might have to go down that route - compiling from TS already creates a `.tmp`)

I'm going to keep playing with it.

**Comment by PaulKinlan** [comment]
Ok - so the following works without any changes to `invoke` node. I make sure that each path I pass into the board has a full absolute path.

``` bash
breadboard run recipes/llm-concepts/rag-query/index.js --kit @google-labs/llm-starter --kit @google-labs/core-kit -i "{\"query\":\"Testing\", \"embeddingBoardPath\":\"$(pwd)/recipes/llm-concepts/rag-query/test-harness/embedding.json\",\"ragBoardPath\":\"$(pwd)/recipes/llm-concepts/rag-query/test-harness/retrieve.json\",\"generateTextBoardPath\":\"$(pwd)/recipes/llm-concepts/rag-query/test-harness/generate-text.json\"}"
```

I do think this is an odd way to work though, I would expect a developer to reason that if they pass in a relative file path it runs relative from where the command is run from.  Thus I think  having the following in the invoke node (for only file paths) makes sense.

```
if (path.startsWith("#") == false) { 
  path = resolve(process.cwd(), path);
}
```

That being said, if we choose to require all paths to be absolute then we need to document this in the `invoke` node (it's pretty vague right now)

**Comment by PaulKinlan** [comment]
I will add - using `Board.load` means that we can't handle spaces in the path (this was something @Mearman brought up a while ago - https://discord.com/channels/1138546999872999556/1138554749537484810/1182484945432748082) 

I have fix: updating `resolveURL` in breadboard\loader.ts to not use `pathname` and instead use `href` (this incorrectly encodes the space as %20 which isn't a valid file path), but it requires also fixing some tests because `test("resolveURL resolves file URLs")` will fail. At the time we didn't know further impacts that this change would have so we left it.

I'm going to update it in this patch and test it.

**Comment by dglazkov** [comment]
> in breadboard\loader.ts to not use `pathname`(this incorrectly encodes the space as %20 which isn't a valid file path) and either use `href` or `decodeURIComponent` (as per Joe).

OHHHH that's what it was! Yes, let's fix it there.

In general, I want URL resolution or any path/URL manipulation to happen at URL resolver layer (exactly where the fix it), and not above it. Above that layer, everything is just URLs.

**Comment by PaulKinlan** [comment]
Path with spaces fix is [here](https://github.com/breadboard-ai/breadboard/commit/f1c9744c181def9ea5990de476ae94c2bf8b8e3b#diff-0bed5dd209406f94a1100403549f4f793bfed6d1052f57937dede26782604b5a) and test is [here](https://github.com/breadboard-ai/breadboard/commit/f1c9744c181def9ea5990de476ae94c2bf8b8e3b#diff-d5599cc943b710aa3a478de2d2d40122038d54c188e8d435d556558ea27f8791R242)

Note: Relative paths passed to `invoke` is not fixed

**Comment by dglazkov** [comment]
> Note: Relative paths passed to `invoke` is not fixed

That should "just work" when using `.load`.

**Comment by dglazkov** [comment]
The basic principle that `load` follows is that URLs are resolved relative to `base` for the top-most board, and then relative to the URL of the outer board that are nested or used as arguments.

**Comment by PaulKinlan** [comment]
I found the cause. Really appreciate the help finding this. Once you explained the relative to the base of the file something clicked (the error that I was seeing was relative to the dist folder and not even relative the input file). I found that I need to set the url on the board properly that was loaded via my cli loader (I think you mentioned this earlier).
