### ISSUE TITLE
Polish and make the September 2024 iteration of VE shine

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3055]
A list of things noticed in the September 2024 iteration of VE. Tracking all comments as todos below

- [x] Bring back the ability to ask for unknown secrets interactively
- [x] #3060
- [x] Figure out output overflow
- [x] Make star wires show even when the "hide advanced ports" setting is set.
- [x] Figure out "saving board" and "updating config" relationship
- [x] Teach VE to paste graphs with star wires

**Comment by dglazkov** [comment]
runJavascript is pretty wide to begin with and grows as config ports are initialized:

<img width="392" alt="image" src="https://github.com/user-attachments/assets/e4a8fa90-e350-4655-b95e-97f8de417aeb">

I am guessing this has something to do with how space is allocated for the minimized view?

**Comment by dglazkov** [comment]
Defining more than 2.5 ports for the input node results in an overflow:

<img width="203" alt="image" src="https://github.com/user-attachments/assets/9c6c9dbb-be3d-42c4-8df7-36833fa665f6">

**Comment by dglazkov** [comment]
Unless we set to show advanced ports in the settings, the star wires don't show up:
<img width="754" alt="image" src="https://github.com/user-attachments/assets/be84e18f-c5a3-4769-b628-384c04c723e5">

**Comment by paullewis** [comment]
On 1, maybe the thing we do is carry "short labels" for each port, which we can use in the footer? I'm reticent to add an overflow to it. We could also consider an additional behavior for ports that should be `quick-access`, and thereby make it more of an allowlist and something we can limit more directly?

**Comment by dglazkov** [comment]
Interesting thing that trips me up when I edit runJavascript node: I can hit Command+Save and save the board while I am inside of the editor, but that will not save the current edits. So I found that I lose my edits like this:

- I open the code config editor
- Make some changes
- Hit Command + Save
- Hit Update in the code config editor
- Reload
- Changes were not saved.

Not sure what the solution is... maybe on Command + Save, we always first automatically update the config?

**Comment by dglazkov** [comment]
Not sure how to solve this one yet. If a field is not marked with "config" behavior, I can no longer configure it. For instance, in this component, I want to specify URL, but I can't do it by clicking on the port name:

![image](https://github.com/user-attachments/assets/432a63d3-b14b-4ade-85a2-4845fb58fe06)

**Comment by dglazkov** [comment]
Now I want to be able to maximize the configure window 😆 

This feels a bit cramped

![image](https://github.com/user-attachments/assets/beafcdbc-6617-4d65-8beb-b1b9d3e74434)

**Comment by dglazkov** [comment]
> are we mostly saying we should bring back the `*` ports and not have the advanced ports toggle?

That does sound better than what I was imagining! Yeah, I wonder if the collapsed/expanded is a tri-state: "collapsed", "expanded", "advanced"?

**Comment by dglazkov** [comment]
> > are we mostly saying we should bring back the `*` ports and not have the advanced ports toggle?
> 
> That does sound better than what I was imagining! Yeah, I wonder if the collapsed/expanded is a tri-state: "collapsed", "expanded", "advanced"?



> > are we mostly saying we should bring back the `*` ports and not have the advanced ports toggle?
> 
> That does sound better than what I was imagining! Yeah, I wonder if the collapsed/expanded is a tri-state: "collapsed", "expanded", "advanced"?

Landed in #3107

**Comment by dglazkov** [comment]
Noticing massive memory usage, even with two tabs, trying to figure out what's happening....

**Comment by dglazkov** [comment]
Fixed in https://github.com/breadboard-ai/breadboard/commit/9783ba8cccfa80806951fdddf032500f672cff04

**Comment by dglazkov** [comment]
Moving all the bugs to #2993
