### ISSUE TITLE
Figure out a more elegant way of stopping runs

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3079]
In https://github.com/breadboard-ai/breadboard/commit/24dd1d1a51b704a947ae4be6217fa091beb24068, I added a bunch of `closeTab` statements in `packages/visual-editor/src/runtime/board.ts` that are all likely bugs or hacks at the very least.

The basic problem I was trying to solve is this use case:

1. Open a board
2. Start a board
3. Then choose another board from the board provider/selector

Before this change, the "Stop Board" becomes stuck and we can no longer stop or start the board.

After this change, the activity button changes to "Start Board".

However, this change might be wrong, because it assumes that we're always closing existing when opening a new board. This is indeed the case for now, but in the future ✨  will be different. And then, this fix will bite us in the butt.

**Comment by paullewis** [comment]
Alright, so this was a fun puzzle!

The additions in https://github.com/breadboard-ai/breadboard/commit/24dd1d1a51b704a947ae4be6217fa091beb24068 were really great, but they were somewhat working around the fact that:

1. We only have one board status in `bb-main`.
2. We were ignoring events for any runner that _isn't_ associated the current tab.
3. We don't support multiple tabs.

The fixes in #3089 are:

1. We always observe a runner's events, but only those for the current tab trigger a re-render.
2. We use those events to handle a board status associated with a tab so if – say – a run finishes while we are observing another tab, we can update the UI when we switch back to the original tab.
4. We support multiple tabs! 🥳 
5. We track the transform applied for a given graph in the graph renderer so they look correct as we move between tabs.
