### ISSUE TITLE
Reloading the page clears all but one tab

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3154]
Example: working in localhost, have several tabs open. vite refreshes – all but one gone.

What’s the right behavior? Not sure. Like, should it also restore runs? I guess?
Should this be like a session state?

I don’t want to lose my tabs.

Also, reloading the page when focused on the run tab will often not work.

Example: try to run a simple board with a Specialist. Click into the Specialist. Reload. This happens because the Specialist board URL is contrived (I didn't realize it was important back then 😆 )

**Comment by paullewis** [comment]
I think this relates to #3152 inasmuch as I think we need to figure out what it looks like to have run, descriptor and URL tabs... and maybe others?

I _suspect_ what we need to do is have a Tab Manager that interprets the URL and opens tabs for everything the URL indicates. So something a bit more than `loadFromURL` or `loadFromDescriptor`, which we have today.

One thing I'm mindful of is the ability to share URLs, though. Today we have `?board=someurl`, which works great for boards that are – say – built-in examples or generally available over HTTP. If we have a URL that is constructed from various sources, such as descriptors and runs, we'd have to give some thought to how we handle URL sharing.

**Comment by paullewis** [comment]
I've landed a fix for this such that tabs that are backed by a URL will be persisted between runs. The existing `?board=` param is remapped to `?tab0=`, but in general all board URLs are represented as `?tabN=`. I've also updated the "Copy Board URL" overflow menu item to be the complete VE URL... but I can always revert that if needed. Wasn't sure if it was used much now.
