### ISSUE TITLE
Unable to run Rhyme of the Day guide

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3201]
When I run https://breadboard-ai.web.app/?board=https://breadboard-ai.github.io/breadboard/static/boards/first-tool/final.bgl.json I find that the tool output is no longer emitted by the Date Retriever, so the board hangs.

**Comment by dglazkov** [comment]
@aomarks I think specialist conversion broke this. The tool output looks like an empty object

**Comment by dglazkov** [comment]
Reverting the conversion for now: https://github.com/breadboard-ai/breadboard/pull/3204
