### ISSUE TITLE
Open Component Configuration on Command + Enter

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3257]
I wonder if we could open component configurator on command + enter... Like, if I click on a component in Visual Editor, then hit Command + Enter -- can I get a configurator window?

**Comment by dglazkov** [comment]
@paullewis

**Comment by dglazkov** [comment]
Command + click? I don't know.

**Comment by paullewis** [comment]
Yeah the interaction model is a little off with the new configurator here. I need to ponder it a little.

**Comment by paullewis** [comment]
Declaring victory for the time being. I think we still want to resolve control ports, * ports and $error, but that's slightly different.
