### ISSUE TITLE
Board server doesn't allow OPTION as a valid verb for API endpoint

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3341]
For the API endpoint, the current routing doesn't allow OPTION to be a valid verb.

This means that CORS calls from the client will fail.

**Comment by wfaithfull** [comment]
I will try and incoporate this into #3172 #3340

**Comment by dglazkov** [comment]
This should work now. Let me test real quick...

**Comment by dglazkov** [comment]
Sorry, fell asleep. Works now!

**Comment by dglazkov** [comment]
Split the express bits into #3401

**Comment by dglazkov** [comment]
Declaring victory 🚢
