### ISSUE TITLE
Components panel width and resizing

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#3353]
Width:
The components panel should be 240px wide and ideally resizable. To make this more effective, I'd like to rewrite the helper text to be briefer and more succinct to improve usability. Copy suggestions forthcoming.

Sticky:
When resized, the component's panel should be sticky when opened and closed.

**Comment by donsbach** [comment]
I'll edit the text and give it to you.

Sticky:
I was thinking it would be nice to have the resize handle on the components panel and it would maintain the size if closed and reopened.

**Comment by paullewis** [comment]
Fixed in https://github.com/breadboard-ai/breadboard/pull/3383

@donsbach are you okay to open a new bug for the text change?
