### ISSUE TITLE
[FR] Add `description` to Board Server listing

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3434]
Currently `/boards` does not include the board description. If we add it then the Board Server Kit listing will be able to use it.

**Comment by dglazkov** [comment]
Would something like 
```json
[ { "url": "board-url", "title": "title", "description": "description" } ]
```
work?

**Comment by paullewis** [comment]
I think it's mostly adding the description because IIRC we have tags, title, owner and so on already?

**Comment by dglazkov** [comment]
Ah got it! I need to think about how to implement it. Currently, I don't save description as a separate field...
