### ISSUE TITLE
Rock-tumbling Board Server Architecture

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3436]
Issues found when playing with the new Board Server Architecture:

- [x] FSAPI doesn't seem to load boards. Click on a board shows "Unable to load board" and in console, the message is  "Unable to load graph from file://welcome/nodes-wires-ports.bgl.json"
- [x] Creating a new board on an expired FSAPI Access seems to just time out and no error message is issued
- [x] Can't create new boards on remote board server

Get this error:
![image](https://github.com/user-attachments/assets/61427d9b-7e60-47d1-8892-917160750892)

In console, it looks like it's trying to use the server title as the URL

- [x] Not related to board server, but just noticed: "Read-only view" lost its styling
![image](https://github.com/user-attachments/assets/6108ba8d-6418-4e3a-8cf1-5c21e2c7952b)

**Comment by paullewis** [comment]
Thanks for taking it for a spin, I'll see what's up with those issues

**Comment by paullewis** [comment]
They were fun puzzles! Hopefully it's all behaving itself now. Can you give it another whirl?
