### ISSUE TITLE
[FR] All runJavascript to throw into $error

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3457]
I have to do some checks on some data coming back from an API to ensure that the value I get is valid. It's possible that the API will return an empty array, in which case I will eject from the board. The way I'm currently trying to do this is to use a `runJavascript` that checks the value and throws if there's a problem. I had expected that any such error would trigger the $error port, but it doesn't. Would it be possible to make that a thing? Or is there another way I should do error handling?

**Comment by dglazkov** [comment]
Can haz an example?
