### ISSUE TITLE
Make it possible to run one component in isolation

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3474]
- [x] Implement "Run from here"
- [x] Teach "Run from here" to recreate historical edge values.
- [x] Update edge value machinery to correctly reflect how values are passed over the edges
- [x] Teach VE to run board step by step
- [x] Allow editing values before each step.
- [x] Synchronize InspectableRun with TGO so that the board activity is in sync when node is edited.
- [x] #3528

**Comment by paullewis** [comment]
A few running notes:

 - I wonder if we should make the "Debug Board" option do this step-wise work? (Or maybe we have "Run" and a "Run Debug")
 - On a related note, it then feels like you want a "next step" option somewhere.
 - When I go to the next step I see the wire value as consumed before I've run the next component: ![Screenshot 2024-10-15 at 10 12 31](https://github.com/user-attachments/assets/7832c714-0432-4061-b192-149f6613d225)
 - I know we currently identify the next opportunity, but in the case above there are two "equivalent" opportunities and I wonder if we need to identify those?

**Comment by paullewis** [comment]
Further thoughts having played with it for a while:

1. I love it.
2. When I edit the value of a node and run it I really want to see its output in the Board Activity. It feels off that it needs to be consumed by an output first somehow. I think we can get there with edge emit, as per the above.
3. I find myself knowing it's a run, but then being confused as to why it stopped. So I feel like we need to really telegraph to the user that execution is paused waiting for them to decide what to do next. I think this is a great opportunity in the Board Activity to have "Carry on from here" and "Re-run this component" options.

**Comment by dglazkov** [comment]
Declaring victory, let's track new features/bugs separately 🚢
