### ISSUE TITLE
Use ES modules for runCode

### ISSUE THREAD

**Issue by surma** [breadboard-ai/breadboard#3482]
I was a bit confused by the fact that I had to specify both the code and the function name in the “Run JavaScript” node.

I was thinking it could be done another way:
- Expect an ES module and always invoke the default export.
```js
export default function() {
  // bla
}
```
- The code should get turned into a blob URL `const codeUrl = URL.createObjectURL([code], {type: "application/javascript"})`, which can then be easily used with dynamic import `(await import(codeUrl)).default(parameters)`.
- In fact, for the browser runtime, I’d suggest running each code node inside a worker inside a iframe that has a Blob URL as a source. That way, the iframe has an opaque origin and there is no way for the user code to access BB’s localStorage or anything.

**Comment by dglazkov** [comment]
Yes! The path here is to build a new discrete (low-level) component with these semantics and then deprecate runJavascript.

**Comment by dglazkov** [comment]
> I’d suggest running each code node inside a worker inside a iframe that has a Blob URL as a source. That way, the iframe has an opaque origin and there is no way for the user code to access BB’s localStorage or anything.

Oh! That would work. Does that mean that we don't need quickjs in the browser? I kind of still want to use it for consistency across platforms.

**Comment by surma** [comment]
You definitely don’t need QuickJS. The worker-in-iframe sandbox is pretty good. What a Wasm-based sandbox gives you is that you can preempt/pause even synchronously running JavaScript and that you have extremely tight control over what is available and accessible from the sandbox’ JavaScript scope, at the cost of execution performance.

**Comment by dglazkov** [comment]
ok, I have the skeleton of the runModule component implemented. It's using just the simplest thing you mentioned in OP, not even workers or anything. But it does work!

I then tried to be fancy and added TypeScript transpilation to the code and this is what happened:
<img width="2000" alt="image" src="https://github.com/user-attachments/assets/0f1bc566-7ad0-4bcb-9722-68bdb7be6dbc">

(the big blob on the right is TS lib)

So I slowly backed away from that idea like nothing happened.

**Comment by dglazkov** [comment]
Declaring victory 🚢
