### ISSUE TITLE
Show the original name/type of a node somewhere.

### ISSUE THREAD

**Issue by surma** [breadboard-ai/breadboard#3486]
For example, inside the built-in “Gemini API Call” board, there is a “Make API Call” node. By the looks for it, it’s just the normal Fetch node, but it doesn‘t tell me that anywhere. That would be nice to show somewhere.

On that note: Would probably be interesting to add a visual marker whether a node is a primitive node or a board that I can drill further into.

<img width="1014" alt="Screenshot 2024-10-14 at 12 08 46" src="https://github.com/user-attachments/assets/4b338798-5257-4927-97a3-3765b18f6c9c">

**Comment by paullewis** [comment]
In the Settings we support "Show Node Type Descriptions", which adds them to the graph. They can be added to the overlay title, however, which I think would be a good thing, and I can default "Show Node Type Descriptions" to `true` by default.

**Comment by paullewis** [comment]
+1. As of #3488 landing the default is to show type descriptions, but only when it differs from the title. The type is also shown in the overlay with the same criterion.
