### ISSUE TITLE
[visual-editor] Line height on Activity Marker

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3494]
Seems little bit off

**Comment by dglazkov** [comment]
![image](https://github.com/user-attachments/assets/bf22e264-7738-4149-9b8e-d349d4645e57)

Is that what you mean? It kind of reminds me of those rotating number displays:

https://www.gettyimages.com/detail/video/visual-display-of-1956-gas-pump-usa-stock-video-footage/102498883

...

Now I kind of want our counter to do the rotation 😆
