### ISSUE TITLE
☂️ Implement Google Drive board server

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3595]
This is the umbrella bug for implementing a board server backed by Google Drive.

- [x] Switch the Drive server picker to use stable folder
- [x] Switch to use `https://www.googleapis.com/auth/drive.file` scope.
- [x] Implement continuous token refresh
- [x] Ensure the toasts are behaving correctly for longer actions
- [x] Less Windows 95 UI for adding a board server
- [x] Add a way for the user to name the folder when adding a board server
- [x] Deleting a board from the sidebar does not refresh the view
- [x] Handle user deleting the board server folder in Drive
- [x] Acknowledge the user's actions more cleanly (particularly loading from Drive)
- [ ] Move it from under the flag

**Comment by dglazkov** [comment]
Copying old description for posterity:

> The basic idea is that we'll have a stable (marked with `appProperties`) "Breadboard" folder in the user's Google Drive, that we'll use as the storage layer for the board server. 
>
> The logic for finding/creating a stable folder is implemented in the experimental [Get Breadboard Folder](https://github.com/breadboard-ai/breadboard/blob/ef99f4eed87772e3557522e1956a220e1fc8fce3/packages/google-drive-kit/src/components/get-breadboard-folder.ts#L4) component (enable "Show Experimental Components" settings to see it).
>
> In this folder, we will  have a hierarchy of folders (`boards`, `data`, `secrets`, etc.) that reflect the storage layout of a board server.
>
> @paullewis 🌞 💨  I stubbed out the files (see commit below) and would love any help in bringing up the server.

**Comment by dglazkov** [comment]
Ok, here's what I have so far:

- stable folders (marked with appProperties)
- continuous token refresh
- using limited scope
- storing name and tags of the graph in appProperties (now the titles of graph show up, not just url)

**Comment by dglazkov** [comment]
What shall we try implementing next?! 😆

**Comment by dglazkov** [comment]
(adding a few todos)

**Comment by dglazkov** [comment]
Shall we move it from under the flag?

**Comment by paullewis** [comment]
I feel like we might want to figure out the autosave stuff first? But maybe not.

**Comment by paullewis** [comment]
I think we can declare victory though!
