### ISSUE TITLE
☂️ Build out better JavaScript support

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3618]
## Current work

 - [ ] #3572
 - [x] #3692
 - [ ] Upgrade FileSystem Board Server to create directories for projects
 - [ ] Add metadata to FileSystem Board Server for project listings
 - [ ] Add debagel/rebagel support to FileSystem Board Server
 - [ ] Add watch support to FileSystem Board Server so that JavaScript changes trigger rebuilds

## Future work

 - [ ] Convert other kits to runModule?

**Comment by dglazkov** [comment]
Is this mostly obsolete now?

**Comment by paullewis** [comment]
I think so.
