### ISSUE TITLE
Mouse wheel scrolls vertically rather than zooming

### ISSUE THREAD

**Issue by surma** [breadboard-ai/breadboard#3624]

**Comment by paullewis** [comment]
Can you tell me more about where you're seeing this?

**Comment by surma** [comment]
On the canvas. If I scroll with my mouse's wheel, the canvas view scrolls up and down, when I would expect it to zoom in and out. But maybe my expectation is wrong?

**Comment by paullewis** [comment]
You can cmd/ctrl + wheel to do that if you like. We've been around the houses on this one a few times, with some folks preferring scroll to zoom, others preferring scroll to move 😄

**Comment by surma** [comment]
Who wants to scroll with the mouse wheel on a 2D canvas? Absolute madness.

No that's fair. Closing this if this an intentional decision. A setting might be nice at some point tho.
