### ISSUE TITLE
Can you delete subboards?

### ISSUE THREAD

**Issue by surma** [breadboard-ai/breadboard#3634]
Can't seem to figure out how 🤔

**Comment by paullewis** [comment]
Yes, the delete button in the ribbon menu allows you to delete a (sub)board. If you have suggestions on where it could be placed to be more useful I'd be happy to hear!

**Comment by surma** [comment]
oh... I feel silly now. I kinda assumed that would delete my currently selected nodes or something.

This is probably good placement, although one idea I have had is to have the delete button inside the subboard switcher dropdown.

**Comment by paullewis** [comment]
I like this idea. I'll give that a whirl.
