### ISSUE TITLE
☂️  Make Module Editing experience amazing

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3711]
Here's a running log of issues/feature requests found while playing with alpha-alpha-v0 of module editor:

## Done

- [x] Add language selection
- [x] Add default module language option to settings
- [x] Add format before save
- [x] Add line numbers
- [x] Make clicking on new code window put the cursor on first line
- [x] Make Cmd+s a shortcut for "Apply Changes" and Save
- [x] Somehow surface Prettier errors and make it resilient in the face of errors
- [x] Make "Preview" available right after "runnable" is checked (without an extra "Apply Changes")
- [x] Propagate the shape (describer) changes when switching to main board
- [x] Add a way to jump to editor from "Run Module" configurator
- [x] Use https://github.com/val-town/codemirror-ts (or port all the features)
- [x] Make overlay floaty
- [x] Prevent deleting unsaved changes in module editor when switching tabs
- [x] Light up "Apply Changes" when pasting code into editor
- [x] Light up "Apply Changes" after clicking on "Format" icon

## Later

Note: it looks like we'd need a mirror of the files for compilation work on main because the TS environment isn't transferable.

- [ ] Move TS support to a Worker

**Comment by dglazkov** [comment]
Should component preview be a floaty? It feels like it's taking a lot of space otherwise.

**Comment by dglazkov** [comment]
In a new window, clicking on the window itself doesn't bring the cursor to it. You have to click on the first line.

**Comment by dglazkov** [comment]
after clicking "Runnable", I have to apply changes to make the preview button available, which seems like an extra step.

**Comment by dglazkov** [comment]
> switching between tabs deletes all unsaved changes in the code editor

Maybe offer to apply changes?

**Comment by dglazkov** [comment]
Clicking Cmd+S makes "Apply Changes" grayed out, but doesn't actually save changes to module

**Comment by dglazkov** [comment]
Switching from module editor to board editor does not update the shape of the module. Steps to repro:

1. Go to module editor
2. Change describer shape (input or output schema)
3. Click "Apply changes"
4. Go to "Main Board"
5. The shape is still the one before change

**Comment by dglazkov** [comment]
Weirdly, I really like that I have "Run Board" in module editor. Creates a very quick edit/try cycle. Not sure what to do about this insight.

**Comment by dglazkov** [comment]
"Apply Changes" doesn't light up when pasting code into the editor. I need to make a one-character change to make it available.

**Comment by dglazkov** [comment]
I'd like to have line numbers

**Comment by dglazkov** [comment]
Format on save

**Comment by dglazkov** [comment]
Clicking on format icon doesn't light up "Apply Changes".

**Comment by dglazkov** [comment]
prettier dies after reporting an error. It seems like I need to reload the page to bring it back.

**Comment by dglazkov** [comment]
in TS, editing the code and saving doesn't seem to update the module code -- only the  source code.

**Comment by paullewis** [comment]
Can we declare victory?

**Comment by dglazkov** [comment]
always!

**Comment by paullewis** [comment]
Declaring victory - let's open new bugs for any quirks we find 👍🏻
