### ISSUE TITLE
Copy raw JSON from JSON viewer

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#377]
Often, I want to grab the actual JSON from the JSON viewer. It would be amazing if I could just select and copy, or maybe have a button that lets me do that.

@paullewis

**Comment by paullewis** [comment]
A stellar idea! I'll sort that tomorrow 👍🏻

**Comment by paullewis** [comment]
By tomorrow I apparently meant "today" (had a little spare time).

**Comment by dglazkov** [comment]
🥳
