### ISSUE TITLE
[FR] Add `description` to Board Server `/list` route

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3781]
Then it can be used for the Remote Board Server listing

**Comment by dglazkov** [comment]
I am not sure I understand this one. Did you mean like here?
https://breadboard.live/boards
It already has descriptions for newer boards, but because of the way I implemented, each old board (pre-description) needs to be saved again to add the description 😆

**Comment by paullewis** [comment]
Ah okay, then it's just that I'm dealing with older boards!
