### ISSUE TITLE
☂️  Project Side Quest: Bring subgraphs into main board view

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3788]
The umbrella bug for all the things to make it happen:

## Plumbing

- [x] Come up with a useful sample board that uses side wires 
- [x] Expose side wires in `InspectableGraph`
- [x] Introduce `EditTransform` abstraction
- [x] Add `MoveToSubgraph` transform
- [x] Add `MergeWithMainGraph` transform
- [x] Add `CreateSidewire` transform
- [ ] Add `RemoveSidewire` transform
- [ ] Add `sideEdges` to `InspectableGraph`

## UI
- [ ] Come up with an alternative way of selecting graphs for invocation

**Comment by dglazkov** [comment]
Quick design sketch:

## BGL bits:

- From BGL perspective, side wires are actually input ports on a node, with the behaviors `board`, `config`, and `sub`. We may deprecate `sub` eventually, after we teach our machinery to wire visually to external boards.
- we'll start with one side wire port per node, but account for allowing more than one in the future
- the port type will be `string` (single side wire) or `array` of `string` (multiple side wires per port).
- the values supplied to the port must be (for now) in the format of `#[uuid]`, where `[uuid]` is the id of the sub-board. All other values will be ignored

## InspectableNode bits:

- From `InspectableNode` perspective, when a side wire is detected, it is moved to `sub` ports object
- The `InspectablePort` grows a `sub()` method, which returns true when the port is  a side wire.

**Comment by paullewis** [comment]
Wondering if we can broadly declare victory here? We have #3836 for the remaining bits.
