### ISSUE TITLE
[Inspector/Editor API] Subgraph changes aren't reflected

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3831]
I suspect we're caching too heavily because if I create a new subgraph I can see its contents in the raw graph, but those are not reflected in the `nodes()` list on `InspectableGraph`.

If I brute force a refresh [here](https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard/src/inspector/graph.ts#L570) to be like `this.resetGraph(graph)` then everything shows up as expected.

**Comment by dglazkov** [comment]
oh this is most definitely me
