### ISSUE TITLE
Embedded Breadboards don't work

### ISSUE THREAD

**Issue by nlothian** [breadboard-ai/breadboard#3850]
## Expected Behavior

The Breadboard should load

## Actual Behavior

The Breadboard doesn't load

<img width="752" alt="image" src="https://github.com/user-attachments/assets/ad1ea8a8-27a1-4f19-9bcb-6e262ac7006c">

Firefox error:
```
Uncaught (in promise) TypeError: e.nodes is undefined
    rebuild https://breadboard-ai.github.io/breadboard/js/board-embed.js:1
    rebuild https://breadboard-ai.github.io/breadboard/js/board-embed.js:1
    g_ https://breadboard-ai.github.io/breadboard/js/board-embed.js:1
    b_ https://breadboard-ai.github.io/breadboard/js/board-embed.js:1
    Gi https://breadboard-ai.github.io/breadboard/js/board-embed.js:1
    loadBoard https://breadboard-ai.github.io/breadboard/js/board-embed.js:2400
16 board-embed.js:1:49575
```

Chrome Error:
```
board-embed.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at g_.rebuild (board-embed.js:1:49595)
    at Tm.rebuild (board-embed.js:1:51801)
    at new Tm (board-embed.js:1:50806)
    at b_ (board-embed.js:1:50657)
    at Gi (board-embed.js:1:53915)
    at Rc.loadBoard (board-embed.js:2400:2407)
```

## Steps to Reproduce the Problem

1. Visit https://breadboard-ai.github.io/breadboard/docs/guides/librarian/
2. Look at the breadboards (which aren't there)

## Specifications

- Version: not entirely sure, but when creating new breadboard it says v1.23.0
- Platform: MacOS, Firefox 132.0.2 (aarch64)
- Tested in Chrome 131.0.6778.86 (Official Build) (arm64)

**Comment by nlothian** [comment]
Example page where they are failing: https://breadboard-ai.github.io/breadboard/docs/guides/librarian/

**Comment by dglazkov** [comment]
Yikes! We broke it!
