### ISSUE TITLE
Distinguishing stateful and stateless nodes

### ISSUE THREAD

**Issue by seefeldb** [breadboard-ai/breadboard#39]
Right now they look the same, but I think only `localMemory` is actually stateful. For all the others the state is entirely captured by the incoming edges, and the same underlying handler works for all instances. For stateful nodes, instances have to be distinguished (is the suggestion in google/breadboard-ai#34 related to this?).

One way we could make this explicit is by introducing an explicit `@self` wire that loops back to itself. The latest value would be passed in with each invocation. Internally, this could just be a pointer into another data structure, it doesn't have to be the actual full state.

This allows distinguishing two such nodes in a single graph. And we can keep one handler instance per node type.

It also opens the door for e.g. a `@clone` or `@mirror` endpoint that `@self` can be wired to. This can be useful when creating subagents that fork a memory, etc.

This makes all data flows explicit in the graph, which is important for the safety work.

One downside is that this self-wire has to be added when building a graph. Maybe that's actually good though, making the distinction with stateless nodes explicit. Or we add a helper that automatically adds a missing self-wire?

WDYT @dglazkov ?

**Comment by dglazkov** [comment]
We are awesome!
