### ISSUE TITLE
No smooth animations

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3905]
On one of my machines, there are now buttery-smooth animations that move components into view. On another machine, it's just a jerky jump. See below:

https://github.com/user-attachments/assets/43cd9eb6-cd1e-42a2-b601-25bfa217bf55

Both are MBPs with very similar specs

**Comment by paullewis** [comment]
By any chance have you switched on "reduced motion" on the second machine, because we honor that flag if you've set it and we don't animate. Quick check: `window.matchMedia("(prefers-reduced-motion: reduce)").matches`

**Comment by dglazkov** [comment]
returns false

**Comment by paullewis** [comment]
Well that's ... odd. Can you try again with tip-of-tree?

**Comment by dglazkov** [comment]
still don't see animations..  I wonder what's going on. Is there something I can check in DevTools to get glean insights?

**Comment by dglazkov** [comment]
Ok, so on the non-animating MBP, the value is always false, because it is only called from here:

https://github.com/breadboard-ai/breadboard/blob/f79278038e77235454ded92e9733aa5d8b12ee31/packages/shared-ui/src/elements/editor/graph-renderer.ts#L1618-L1622

**Comment by paullewis** [comment]
The general difference between the two cases is whether we are creating new graphs or updating existing ones. In the case where we are creating new graphs we assume it's a tab switch or a board load where we wouldn't want to animate. All other cases, particularly around selections, are usually graph updates and we animate those. I'm not entirely clear why we would animate updates on one MBP but not another!

**Comment by dglazkov** [comment]
you will not believe this. It just started working for no reason. Can't repro anymore.

**Comment by dglazkov** [comment]
hmm and now it's back to no animations.

**Comment by dglazkov** [comment]
oh interesting! It only seems to skip animations when in this state:
![image](https://github.com/user-attachments/assets/88e48e08-1e89-42d3-9260-fcd8c56ebc1a)

I wonder if there's some math around the number of configs?...

**Comment by paullewis** [comment]
Ah, it's because in that mode we swap graphs entirely so there's no animation. Initially I had the animation on when swapping between the boards and it was very jarring. So... WAI?

**Comment by paullewis** [comment]
This mode is causing more issues than I'd like, so I'm going to remove it and find a better way to organize the Workspace.
