### ISSUE TITLE
Can't copy board outputs

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3969]
1. Produce board output
2. Try to copy board output
3. Graph is selected instead
4. Pastes the graph descriptor

**Comment by dglazkov** [comment]
This was reported by Anthea and Nick on Discord -- they are running their own Visual Editor internally, so they've spotted this before we deployed the new selection stuff to our public VE.

**Comment by nlothian** [comment]
Not sure this is fixed. See the loom here: https://www.loom.com/share/9496810b01f34a658909c4bf91a57ff6?sid=a123b373-594b-48f6-9270-194ba65f33a8

I deployed commit ID `66105f9f0dc8053e96066866c66c7f63ca1351e6`

**Comment by paullewis** [comment]
> Not sure this is fixed. See the loom here: https://www.loom.com/share/9496810b01f34a658909c4bf91a57ff6?sid=a123b373-594b-48f6-9270-194ba65f33a8
> 
> I deployed commit ID `66105f9f0dc8053e96066866c66c7f63ca1351e6`

I think that commit is too old to have the fix.

The fix was landed in de75b637d64b733403a6dba625f2a9de43960c8e on the 10th December, whereas the commit you deployed was from the 3rd December. If you pull to the latest and deploy that you should get the fix.
