### ISSUE TITLE
Too many WebGL contexts error

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3999]
![image](https://github.com/user-attachments/assets/bb10bd2c-0c68-4287-ad89-67a673d1f7ae)

Nothing bad seems to happen when I got it, but in the past, it would result in the editor going blank blue.

**Comment by paullewis** [comment]
Is this in the Visual Editor or the website? The latter would make sense because we do spin up individual renderers for boards, but we shouldn't see it in the Visual Editor because we should be using a single context the whole time.

**Comment by dglazkov** [comment]
Yep, in Visual Editor

**Comment by paullewis** [comment]
Ah, I figured out what it is. It's because when you close a tab we disconnect the graph renderer but we don't dispose of the Pixi app, which means the context sticks around. I'll sort a fix.

**Comment by paullewis** [comment]
Fixed
