### ISSUE TITLE
Embedded boards in the docs don't show.

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#4005]
I was trying to get my head around the Looper in AgentKit, so I went to https://breadboard-ai.github.io/breadboard/docs/kits/agents/

and saw

<img width="767" alt="Screenshot 2024-12-13 at 8 07 45 PM" src="https://github.com/user-attachments/assets/a39183bd-f4ee-41dd-90a7-2e3709eec9f3" />

**Comment by dglazkov** [comment]
Getting this error in console:

```
Uncaught TypeError: U(...).value.toContainerCoordinates is not a function
    at $e.iw (board-embed.js:448:3323)
```

**Comment by dglazkov** [comment]
@paullewis does that sound familiar? Maybe all the recent shifts in the visual editor?

**Comment by paullewis** [comment]
That does sound familiar, though it's a bit odd. I'll look.

**Comment by paullewis** [comment]
Fixed in https://github.com/breadboard-ai/breadboard/pull/4024
