### ISSUE TITLE
Improve display of errors in debugger

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#461]
- [x] Occasionally, the json-agent throws an error when the JSON output is invalid. This error is currently only visible in the DevTools console
- [x] "missing parameter" errors show up only in DevTools.

**Comment by paullewis** [comment]
@dglazkov How would I replicate the `"missing parameter" errors show up only in DevTools.` issue?

**Comment by dglazkov** [comment]
A good way to do this is to leave off connecting to the `expression` input port of the `jsonata` node. It will complain that it needs `expression` to function

**Comment by paullewis** [comment]
In which case we can probably declare victory :)

**Comment by paullewis** [comment]
The errors are propagated out to the outputs panel; happy to add more to this if we feel it needs it. For now, though, declaring as done!
