### ISSUE TITLE
Ship first iteration of Breadboard doc site 

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#510]
Here are the sections that we'll need. For each section: complete, edit, check for accuracy:

- [ ] Kits inputs/outputs documentation (stretch)
- [ ] New syntax documentation (stretch)

**Comment by aomarks** [comment]
Split out into a bunch of issues:

https://github.com/breadboard-ai/breadboard/issues/524
https://github.com/breadboard-ai/breadboard/issues/523
https://github.com/breadboard-ai/breadboard/issues/522
https://github.com/breadboard-ai/breadboard/issues/521
https://github.com/breadboard-ai/breadboard/issues/520
https://github.com/breadboard-ai/breadboard/issues/519
