### ISSUE TITLE
Should we publish `breadboard-web`?

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#529]
It's kind of a mishmash of all the things (see #206), but the current `breadboard-cli` depends on it, so it needs to be published.

Shall we:

1. Publish it as is?
2. Rename to `breadboard-debugger` and publish?
3. Do something more elaborate?
4. ???

@PaulKinlan @paullewis @aomarks 🪙 for your thought

**Comment by PaulKinlan** [comment]
Yeah - I'd like it published (it was one of the reasons why I used to just copy the dist folder). I'm pretty open to the other pieces with no specific opinions :D

**Comment by dglazkov** [comment]
shall we optimistically rename it to `breadboard-debugger`?

**Comment by dglazkov** [comment]
Declaring victory 🚢
