### ISSUE TITLE
Preview doesn't work in `breadboard debug`

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#577]
When clicking on "Preview" 
![image](https://github.com/breadboard-ai/breadboard/assets/1934/5dfbb592-acfc-46e7-b644-35f218663045)

I get this in DevTools console:

![image](https://github.com/breadboard-ai/breadboard/assets/1934/488491f2-eeb5-42f1-99e9-2bf55d452900)

I am guessing some files are missing maybe? Or logic?

**Comment by paullewis** [comment]
Ah this usually happens when the web server does a rewrite of the preview URL and casually removes the search params. I'll take a look.

**Comment by paullewis** [comment]
Aye, the change was here: https://github.com/breadboard-ai/breadboard/commit/2b105e084608306e9471c647b6ff8f9bba6c639c#diff-d91b32ed90d91eb4b06379bf47fe78decec71153dfc5cdf14210163596c34db6R146 – just finding out why.

**Comment by paullewis** [comment]
Looks like there might be a case where something doesn't work, but it's not clear. So I've reverted it for now, but in the event we find a case where the lack of clean URLs is causing problems, I'll fix it.
