### ISSUE TITLE
[FR] Support Markdown outputs

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#589]

**Comment by Mearman** [comment]
From nodes, or of boards?
In our kits package, I ended up writing utility functions to output boards to MD, with the mermaid and/or json.

**Comment by paullewis** [comment]
@dglazkov We don't currently emit a `markdown` behavior anywhere, but if we do I think I should be able to wire this one in pretty quickly.

**Comment by dglazkov** [comment]
I should totally add it in at least one place ...

**Comment by dglazkov** [comment]
Tour guide writer now has `format: "markdown"`!

**Comment by dglazkov** [comment]
I also just realized something related: most of the time, LLM output expects to render in whitespace-preserving way. Like this poem:

```
A board of plastic, holes in rows,
For circuits temporary, as everyone knows.
No soldering required, just wires to poke,
A playground for electrons, where circuits awoke.

LEDs blink, resistors resist,
Capacitors charge, transistors persist.
A breadboard's a canvas, a playground to test,
Ideas take form, put to the quest.

From simple circuits to complex designs,
A breadboard's the place where creativity aligns.
So grab your wires, your components too,
And build your dreams, make them come true.
```

However, we render as if it's just HTML content. WDYT about changing the default to `white-space: pre` or something like that? I bet that would go a long way.
