### ISSUE TITLE
How do I Invoke `webcam` from `card-maker`?

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#595]
For the tutorial flow I am writing for M4, I need a way to invoke the [Webcam](https://github.com/breadboard-ai/breadboard/blob/main/packages/hello-world/src/webcam.ts) board from the [Card Maker](https://github.com/breadboard-ai/breadboard/blob/main/packages/hello-world/src/card-maker.ts) board.

I can't figure out how to do it with `breadboard debug src/`.

Both files are in the same directory. Intuitively, this should work:

```ts
core.invoke({ path: "webcam.json"});
```

but it doesn't since the board is actually in TypeScript and there isn't a JSON file in the same directory -- they are generated on the fly. Technically, the do get created, but in the parent directory.

This works:

```ts
core.invoke({ path: "webcam.ts" });
```

But that's not right, since now we have a reference to a TypeScript file embedded into a graph.

I wonder if we need to have a well-established directory (like "boards") where all *.json boards live and the root of that dir is used to resolve the invoke URLs?

**Comment by dglazkov** [comment]
For M4, I will just use the absolute URL:
`https://raw.githubusercontent.com/breadboard-ai/breadboard/8a1c85d897306377e4125ebb59fb3ba0d81eebae/packages/hello-world/webcam.json`

**Comment by paullewis** [comment]
> I wonder if we need to have a well-established directory (like "boards") where all *.json boards live and the root of that dir is used to resolve the invoke URLs?

FWIW that's what I did with the extension; it stores a path you give it about where it can resolve other boards. I guess it also ties into the discussion of having a general resolver so that someone could redirect a lookup. Maybe we have that as an option on a board itself?

**Comment by PaulKinlan** [comment]
All of the boards in `src/**/*` should be getting compiled if you did `src/` - it's a bug if they didn't.
