### ISSUE TITLE
Board not displaying output in debugger

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#610]
I have the Open API board.

<img width="927" alt="Screenshot 2024-02-02 at 18 47 20" src="https://github.com/breadboard-ai/breadboard/assets/45510/aed00874-7379-41fb-ac4a-d4f90ec4573d">

I run it (it works - but it takes a long long time to generate - there seems to be about 1000 APIs). I can see the output in the list (output-2) and it has data. 

I click on it and it's empty

<img width="929" alt="Screenshot 2024-02-02 at 18 47 29" src="https://github.com/breadboard-ai/breadboard/assets/45510/b705b06d-acca-44fe-a6fc-d89ada930c27">

Console log.

<img width="717" alt="Screenshot 2024-02-02 at 18 46 14" src="https://github.com/breadboard-ai/breadboard/assets/45510/a814f26f-a016-4cd7-9eb6-a142eb0cff9f">

**Comment by paullewis** [comment]
Is this working now, or still broken?

**Comment by PaulKinlan** [comment]
I think this was fixed in the new UI.
