### ISSUE TITLE
Create a Gemini Kit

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#625]
This will be a light kit and an experiment: assemble the two boards we have into a kit and see if we can get a good DX out of it (both making a kit and using it).

**Comment by PaulKinlan** [comment]
Linking #516 to this

**Comment by PaulKinlan** [comment]
@dglazkov I'm interested in this (I need to fix up the embedding one that we have to match one of the recipes that I was making for generateText)

**Comment by dglazkov** [comment]
@PaulKinlan there's now a gemini-kit. Lots of work to make it actually work well, but it's there!
