### ISSUE TITLE
Hello world board is empty

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#631]
https://github.com/breadboard-ai/breadboard/blob/main/boards/hello-world.json

**Comment by PaulKinlan** [comment]
Yeah - no clue where that is used.

**Comment by Mearman** [comment]
@PaulKinlan I came across it to use for my isolated tests. Would you mind populating it with something? I'm not sure what *should* be in there.

**Comment by dglazkov** [comment]
Why do we need this?

**Comment by Mearman** [comment]
don't know, but it's there. I came across it when looking for a minimal board for the testing

**Comment by PaulKinlan** [comment]
I don't think we do need it.... @aomarks - I think it stems from this change, https://github.com/breadboard-ai/breadboard/commit/13b8dac4863325ea147c4db721b5a3830fe45ee1#diff-c9e34299d76502e19774a88e28db603e1b9c2e18b05628561cd0f1eac1456b7e

**Comment by dglazkov** [comment]
Gone now.

**Comment by Mearman** [comment]
> Gone now.

haha. I was the one that deleted it in the end
