### ISSUE TITLE
Dependencies aren't resolved for `npm exec`

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#633]
It appears that with `npm exec` the `cli`, `create-breadboard` and `create-breadboard-kit` binaries aren't resolving their dependencies correctly
see: https://github.com/ExaDev-io/breadboard/actions?query=branch%3Aisolated-pipeline

**Comment by PaulKinlan** [comment]
It's hard to tell from that link. I did some checks around npm exec/npx and it always tries to find the closest package.json up to the root on the directory tree

**Comment by Mearman** [comment]
It's when out of tree, trying to use `npx`/ `create` / `init` / `exec`
such as: https://github.com/ExaDev-io/breadboard/actions/runs/7769689266/job/21189040898#step:6:8

**Comment by Mearman** [comment]
not at the bottom of it yet @dglazkov 
doing some more experimentation after looking through https://vitejs.dev/config/dep-optimization-options.html
need to deploy https://github.com/breadboard-ai/breadboard/pull/655 to test

**Comment by PaulKinlan** [comment]
For some extra reference

```bash
(base) paulkinlan-macbookpro2:~ paulkinlan$ npx @google-labs/breadboard-cli run $BOARD -i "{\"message\": \"Hello World\"}"
Need to install the following packages:
@google-labs/breadboard-cli@0.4.1
Ok to proceed? (y) y
node:internal/modules/esm/resolve:844
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'commander' imported from /Users/paulkinlan/.npm/_npx/a707485681ebc14b/node_modules/@google-labs/breadboard-cli/dist/src/index.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v21.6.1
```

**Comment by PaulKinlan** [comment]
I suspect this will be solved by your bundleDependencies.

**Comment by Mearman** [comment]
@PaulKinlan I've had partial success. just working on an in-place deployment for better testing

**Comment by Mearman** [comment]
continuing in https://github.com/breadboard-ai/breadboard/issues/675
