### ISSUE TITLE
Add an option for `breadboard make` to save the board

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#635]
The `-o` option is there, but it doesn't seem to do what I want.

**Comment by PaulKinlan** [comment]
Yeah - totally agree with this.

**Comment by PaulKinlan** [comment]
In this case, I think `-o` was for a place to store the temporary TS files (which is now managed differently)

**Comment by PaulKinlan** [comment]
@dglazkov I'm changing the default up and bringing it inline with debug.

`breadboard make [DIR]` - makes all the boards in dir/**/* and outputs to cwd or `-o DIR`
`breadboard make [FILE]` - makes the file and outputs it to cwd or `-o DIR`
`breadboard make [FILE] -n` - makes the file and outputs it to console.

**Comment by PaulKinlan** [comment]
@dglazkov can you check that the latest implementation does what you need (then we can close this)

**Comment by dglazkov** [comment]
perfect! 🚢
