### ISSUE TITLE
Switching from the "Preview" to "Build" tab in the Debugger web interface duplicates inputs

### ISSUE THREAD

**Issue by jeffposnick** [breadboard-ai/breadboard#637]
## Expected Behavior
The list of input fields in the Debugger web interface should accurately reflect the inputs in the board's schema.

## Actual Behavior
Extra copies of input fields are added to the Debugger web interface.

## Steps to Reproduce the Problem

1. In a newly scaffolded `npm init @google-labs/breadboard breadboard-test` project, run `npm run dev` and visit `http://localhost:3000/`.
1. Choose a board, like "Blank board". You'll start on the Build tab.
1. Switch to the Preview tab, and then back to Build.
1. You'll see an extra copy of the input field for each time to switch back and forth.

<img width="1415" alt="Screenshot 2024-02-03 at 10 35 57 PM" src="https://github.com/breadboard-ai/breadboard/assets/1749548/d5dc6ff6-1fc5-4d00-b6e6-3bdee62acda1">

## Specifications

- Version:
```json
{
  "dependencies": {
    "@google-labs/breadboard": "^0.10.0",
    "@google-labs/breadboard-cli": "0.4.0",
    "@google-labs/core-kit": "0.2.1",
    "@google-labs/template-kit": "0.1.3",
    "@google-labs/json-kit": "0.0.5",
    "@google-labs/palm-kit": "0.0.4"
  },
}
```
- Platform: Node.js v20.11.0 on macOS

**Comment by dglazkov** [comment]
Oh, that's a good one. Thanks for filing the issue!
