### ISSUE TITLE
[FR] An inspection API for boards

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#669]
So looking at visual editing as a feature, I think we need a new API somewhere that greedily consumes the board description and generates:

1. A list of nodes that it found in the board.
2. For each node that it finds, the sets of possible ports (in and out).
3. Edges describing which ports are in use.
4. For sub boards, a list of possible ports (in and out).

While I think we might ultimately want to have all boards and sub boards represented in the API response, I think for a first version we could pass it a board URL / descriptor and work at that level. For any sub board, we would need to know only what the various board level ports are. My quick hack code to get this from our existing structure looks like:

```typescript
const subBoard = await Board.load(path, { base });
for (const node of subBoard.nodes) {
  if (node.type !== "input" && node.type !== "output") {
    continue;
  }

  // Any inputs with incoming edges are excluded.
  if (node.type === "input") {
    const inputEdge = subBoard.edges.find(
      (edge) => edge.to === node.id
    );
    if (inputEdge) {
      continue;
    }

    inPorts.push(node.id);
  }

  // Any outputs with outgoing edges are excluded.
  if (node.type === "output") {
    const outputEdge = subBoard.edges.find(
      (edge) => edge.from === node.id
    );
    if (outputEdge) {
      continue;
    }

    outPorts.push(node.id);
  }
}
```

So working at the current board level would work, at least initially. If we need to go into a sub board's details further, we could make another request to the API with the sub board's URL/descriptor as the starting point.

I think there _might_ be some wrinkles when it comes to boards with multiple outputs, though, because it's possible that a given output _could_ be invoked and we don't necessarily know by analyzing up front. For example, in the Simplest LLM-based board, the Gemini Generator sub-board has a `textOutput` output node with a property `text` on it which happens to match the outer board's output `text` node. Because the names match we wire them together. That particular output on the sub-board fires because we only send the `text` parameter through from the outer board, and the Gemini Generator's other parameters use their defaults, which means `stream` is set to `false`. Thinking out loud though, we _do_ know that if you haven't set the `stream` parameter from the outside then following the graph you shouldn't get the `streamOutput`, so that should be possible to establish up front by looking at defaults and what's being sent through from the outer board.

For things where the input bubbles up, however, we might have to insist that a user handles all possible output ports because we simply don't know.

**Comment by paullewis** [comment]
There's immediate value in this API as it stands - it's a great start! A couple of questions/requests:

1. I find myself walking the nodes to locate the one where isEntry() is true and isExit() is true; this allows me to roughly order the nodes by traversal. Would it be possible to walk the graph as we do for the runner and emit them in some kind of traversal order?
2. When meeting an `invoke` I don't know that I've met a sub-graph, and the node descriptor doesn't allow me to query the sub-board level info.

Making this a bit more concrete, supposing I wanted to query simplest.json, the ideal case would be that I get [node (`input`), sub-graph (`invoke`), node (`output`)] and, broadly, the following info:

## input
```json
{
  "nodeType": "node",
  "id": "input",
  "type": "input",
  "isEntry": true,
  "isExit": false,
  "inputSchema": {},
  "outputSchema": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "title": "Prompt",
        "description": "The prompt to generate a completion for",
        "examples": [
          "Tell me a fun story about playing with breadboards"
        ]
      }
    }
  },
  "incoming": [],
  "outgoing": [{
    "to": "gemini",
    "ports": ["*"]
  }] 
}

```

## Invoke

```json
{
  "nodeType": "subgraph",
  "id": "gemini",
  "type": "invoke",
  "isEntry": false,
  "isExit": false,
  "inputSchema": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "title": "Text",
        "description": "The text to generate",
        "examples": ["What is the square root of pi?"]
      },
      "useStreaming": {
        "type": "boolean",
        "title": "Stream",
        "description": "Whether to stream the output",
        "default": "false"
      }
    }
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "title": "Text",
        "description": "The generated text"
      },
      "context": {
        "type": "array",
        "title": "Context",
        "description": "The conversation context"
      }
    }
  },
  "incoming": [
    {
      "from": "input",
      "ports": ["*"]
    }
  ],
  "outgoing": [
    {
      "to": "output",
      "ports": ["*"]
    }
  ]
}
```

### Output

```json
{
  "nodeType": "node",
  "id": "output",
  "type": "output",
  "isEntry": false,
  "isExit": true,
  "inputSchema": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "title": "Response",
        "description": "The completion generated by the LLM"
      }
    }},
  "outputSchema": {},
  "incoming": [{
    "from": "gemini",
    "ports": ["*"]
  }],
  "outgoing": [] 
}
```

So I think the gap we have today is differentiating between a node and a subgraph, and, when we have a subgraph, flattening its input & output schemas so it appears like any other node. I've tagged each with a `nodeType` just because at some stage in the UI we'll need to differentiate between nodes and subgraphs, where the latter will allow you to "unpack" and peek inside.

**Comment by dglazkov** [comment]
> I get [node (`input`), sub-graph (`invoke`), node (`output`)] in traversal order,

I can't give you a list like that because of all the cycles and branches. It would have to be a traversal API of some sort. Like,

```ts
const entries = graph.entries();
for (const entry in entries) {
  // do something with the `entry`
  // ...
  const outgoing = entry.outgoing();
  // traverse into outgoing edges
  // ...
 }
```

**Comment by paullewis** [comment]
I think so, yes. Let's give that a go!

**Comment by dglazkov** [comment]
The subgraph bits sound right, btw.

**Comment by paullewis** [comment]
I think in general the node/subgraph distinction, along with the subgraph input output schema, is the thing I was feeling more acutely. The ordering is nice to have, and a traversal API seems like a good answer.

**Comment by dglazkov** [comment]
As of https://github.com/breadboard-ai/breadboard/commit/2237a4c8202ef6b182901950dc2f4088a151cb9f, added:

- `InspectableGraph.entries()` that will return the entry nodes
- `InspectableNode.isSubgraph()` that will tell us whether the node contains a subgraph (in retrospect, should have named it `hasSubgraph`)
- `InspectableNode.subgraph()` that returns a subgraph. Note that we need to give it a loader: I started writing the loader bits into the inspector, and realized that this makes it a lot more complicated. So instead...
- `loadToInspect()` function, which create a default loader that should work for most cases.

**Comment by dglazkov** [comment]
As of https://github.com/breadboard-ai/breadboard/commit/d7a79033f6ad4cea6bd13b82019998bf30607e4e:

- the `InspectableGraph.describe` now provides reasonable outputs: the inputSchema and outputSchema are derived from input/output wirings and configuration. A couple of examples are in [traversal.ts](https://github.com/breadboard-ai/breadboard/blob/inspector/packages/breadboard/tests/inspector/traversal.ts#L56)
- the `InspectableNode.describe` now works for `input` and `output` nodes. It will throw on any other type of the node for now. Implementing that feels like a good next step.

Please try my 🍪 🍪 . 😆

**Comment by dglazkov** [comment]
Here's what I have so far in terms of various ways to describe the node:

- The `node.incoming()` and `node.outgoing()` describe the actual wiring that is present in the graph. This may or may not match what the node expects.
- The `node.describe()` describes the inputs and outputs the node expects.
- The `(await node.subgraph()).describe()` describes the inputs and outputs of a graph that is being invoked. This peeking under the covers of the `node.describe()`: what does the invoked graph actually want?.

**Comment by paullewis** [comment]
This is working really well for the initial work! (Yay!) When I look at the configuration for `llm` in `gemini-simplest.json` it's currently an empty object. Is this because we only currently "expand" `invoke` nodes as subgraphs?

**Comment by paullewis** [comment]
Also an error gets thrown for `agent.json`:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nodes')
    at new Graph (graph.ts:30:31)
    at inspectableGraph (graph.ts:18:10)
    at index.ts:45:14
    at Node.subgraph (node.ts:70:18)
```

**Comment by paullewis** [comment]
On `ask-user.json` the `invoke` subgraphs seem to be empty:

```json
{
    "inputSchema": {
        "additionalProperties": true,
        "type": "object"
    },
    "outputSchema": {
        "additionalProperties": true,
        "type": "object"
    }
}
```

**Comment by paullewis** [comment]
Nodes like `fetch` and `jsonata` don't currently declare their inputs & outputs anywhere AFAICT. This means we don't get things like `expression` or `url` coming through in the description. Would it be possible to add them?

**Comment by dglazkov** [comment]
> When I look at the configuration for `llm` in `gemini-simplest.json` it's currently an empty object. Is this because we only currently "expand" `invoke` nodes as subgraphs?

yup. the `llm` node is part of the kit, so the board invocation is kind of hidden behind the node. I need to add handling kits to the inspector API and then all nodes will be able to describe themselves.

In this case, however, the node describer also needs to communicate that there's a sub-board. I likely need to add another member to the `NodeDescriberResult`.

**Comment by dglazkov** [comment]
> Also an error gets thrown for `agent.json`:

That's a good one. The path for this invoke is being passed as argument to `agent.json` (it's the `generator`), so that invoke doesn't know what to look for without running the graph.

**Comment by dglazkov** [comment]
Declaring victory 🚢 !

Let's file new issues against the existing inspector API.
