### ISSUE TITLE
[Inspector] node.describe() provides incomplete description of structuredWorker

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#748]
It's possible I'm holding things wrong here, but when I call `node.describe()` against `structuredWorker` in the Ad Writer board I get:

```
{
    "type": "object",
    "properties": {
        "context": {
            "type": "string"
        }
    }
}
```

Looking at the configuration, though, I think there should be something for `instruction` and `schema`?

Interestingly, when looking at a blank board (?mode=build with no board set) and I drag on a `structuredWorker` I get a totally empty configuration back from the Inspector.

**Comment by dglazkov** [comment]
Oops, I forgot to add a describer for it:

https://github.com/breadboard-ai/breadboard/blob/e6ed5911a8bbfd7335b53d44b33b802395253b28/packages/agent-kit/src/index.ts#L35

**Comment by dglazkov** [comment]
Bonus: we now get default/example values from the Kit:

![image](https://github.com/breadboard-ai/breadboard/assets/1934/2937a287-d027-49f1-aaf1-a0f04bf92ce9)
