### ISSUE TITLE
[FR] Return the same objects from the Inspector API on subsequent requests

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#800]
I have been keying cached graphics in the editor based on the objects coming from the Inspector API. Then I realized that I'm getting new – say – edges and node descriptions every time, which invalidates Maps and whatnot because they're, well, new.

If that's a pain (and it might well be) then I wonder if we can add a `toString()` to things like `InspectableEdge` or `InspectableNode` so that I can serialize them and use them as the keys for the graphics. wdyt?

**Comment by paullewis** [comment]
I'm currently working around the edge thing here: https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-ui/src/elements/editor/graph.ts#L26-L28

**Comment by dglazkov** [comment]
I want to implement this first thing you suggested. The rough shape I am imagining is this:
- the `inspect()` method on the `EditableGraph` instance returns a stable `EditableGraph` instance. It's a cheap method to call
- when the `EditableGraph` change/add/remove methods are called, the `inspect()` continues to return the same `InspectableGraph` instance
- preserves unchanged nodes/edge instances
- returns new `InspectableEdge` and `InspectableNode` instances for added edges/nodes
- returns the same `InspectableNode` for `changeConfiguration`, but with the changed `configuration`.

Would that work?

**Comment by dglazkov** [comment]
Both `InspectableEdge` and `InspectableNode` instances should be stable now even across edits. Let me know how it works 🎧
