### ISSUE TITLE
Export agnostic nodes as graphs that wrap opinionated API nodes

### ISSUE THREAD

**Issue by seefeldb** [breadboard-ai/breadboard#83]
To open a discussion:

I propose that when creating nodes that represent external APIs, that they should match the API as closely as reasonable, except maybe a few clear conventions we develop over time for naming things (e.g. that the API key should come in as `<API>_KEY` and not `key`).

And then we can write graphs that wrap these nodes and export an agnostic interface that other APIs can implement as well.

To make it concrete: Should `llm-starter-kit` expose an agnostic text completion node that internally wraps a Palm specific one?
Consider google/breadboard-ai#82 down the road.

And here it would be great to somehow configure starter kit to use a different provider by passing it graphs for these other ones, somehow. Or maybe the generic text completion node actually takes a slot for an implementation, but has a default?

And while we're at it, at this point, what is exported could be a combination of `secrets` and that API specific node, so that starter kit users don't have to wrangle with secrets.

**Comment by dglazkov** [comment]
Yes! All of this has played out (or playing out) as predicted. 🚢
