### ISSUE TITLE
Editor API: Error when moving an edge

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#852]
Got a fun one. To repro:

1. Start with the blank board in edit mode
2. Add a `promptTemplate` and connect `promptTemplate.text -> output.text`. (This will now mean there are two edges going to `output.text`)
3. Drag the edge from `input.text -> output.text` over to make `input.text -> promptTemplate.template` instead. Because we've not disambiguated which of those edges it'll pick the first one (`input.text -> output.text` rather than `promptTemplate.text -> output.text`). In theory we should have `input.text -> promptTemplate.template -> promptTemplate.text -> output.text` but...
4. When you release the cursor you'll get the following error:

```
schemas.ts:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'out')
    at schemas.ts:28:27
    at Array.reduce (<anonymous>)
    at edgesToProperties (schemas.ts:27:16)
    at edgesToSchema (schemas.ts:43:20)
    at Graph.describeType (graph.ts:88:20)
    at #describeInternal (node.ts:62:24)
    at Node.ports (node.ts:80:51)
    at #processGraph (editor.ts:304:48)
```

**Comment by dglazkov** [comment]
This is a fun one. It happens because we have several instances of `InspectableGraph` and `EditableGraph` floating around, and we can't count on the edge/node updates happening correctly.

**Comment by dglazkov** [comment]
The fix is to reduce edge stability a bit, recognizing that some of these `InspectableEdge` instances will be thrown away anyway.
