### ISSUE TITLE
[FR] Editor API: add an edge change method

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#870]
We currently emit two events for changing an edge: one to remove the old edge and one to add a new edge. That said it's possible that one of those operations could fail, so I'm wondering if we want something more atomic from the Editor API: a change method which takes `from` and `to` params? wdyt?

**Comment by dglazkov** [comment]
Yeah, that seems right. And the `from` object identity doesn't change in this case, just the values? This way, it's still the same edge in the graph? Would that work? Or would you rather change identity?
