### ISSUE TITLE
[FR] Allow previewing and/or editing (and pasting in) of board JSON while editing in UI

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#898]

**Comment by paullewis** [comment]
@aomarks Just checking in, is this one you wanted to look at at some stage? (Happy for you to reassign if yes, or leave it with me if no.)

**Comment by aomarks** [comment]
@paullewis I have no plan currently to work on this

**Comment by paullewis** [comment]
I think we're good on this one since we can now copy-paste etc.
