### ISSUE TITLE
Exception thrown by `breadboard debug`

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#922]
When trying to run `breadboard debug` for [worker.ts](https://github.com/breadboard-ai/breadboard/blob/main/packages/agent-kit/src/boards/worker.ts), getting this exception:

```
Failed to load board at "[path elided]/breadboard/packages/agent-kit/src/boards/structured-worker.ts": Failed to load board from source
Error: Dynamic require of "assert" is not supported
```

Investigating...

@PaulKinlan if anything jumps out at you immediately, LMK.

**Comment by dglazkov** [comment]
Figured it out. Need to mark "node:fs/promises", "node:vm" as external.

**Comment by PaulKinlan** [comment]
This is good to know. I will check to see if there are any more.
