### ISSUE TITLE
Default zoom event needs disabling on the UI

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#926]
Found this in the UI @paullewis.
I'm hesitant to call it a bug. More an unexpected behaviour.
Scroll to zoom behaves as expected on the UI, however pinch-to-zoom is still triggering (I assume) the default zoom event.
https://github.com/breadboard-ai/breadboard/assets/1331872/f98fc075-4d26-40bd-92ad-ceebaaa09435

**Comment by alexandraM98** [comment]
@paullewis Still experiencing the issue mentioned above by @Mearman. I will also look into this (including the changes in #955  )

**Comment by paullewis** [comment]
Yeah, I wasn't completely sure I'd solved it, which is why I didn't mark it as fixed. What's the specific context? Mobile or a touchscreen desktop? (Or something else?)
