### ISSUE TITLE
[FR] File loading support for Editor

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#927]
This is definitely one for the future, but to lower the usability barrier, it would be great to load and save boards interactively from Git / Gist / Google Drive.
In the longer term, I'm thinking of usage similar to that of StaticCMS / Decap.

Initially, though, saving to browser storage would be very handy.

**Comment by dglazkov** [comment]
Related #961

**Comment by paullewis** [comment]
We're part of the way there - you can open files from disk now! 🥳

**Comment by paullewis** [comment]
And also IDB

**Comment by paullewis** [comment]
In fact, I think I'll declare victory for now 🚢 

We can add more providers in the future as time allows.
