### ISSUE TITLE
Kit nodes that use `base.input()` to create accept inputs don't render their schema in the Editor

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#931]
I'm using the Gemini Kit to try and build a board, but I can't hook up edges to the node because the  only input is `*`. In the Gemini kit, it looks like the board's schema is very well defined.

It seems that nodes/boards that define their schema as `base.input()` and not as `board({ some_key })` no longer seem to render.

<img width="232" alt="Screenshot 2024-03-01 at 12 24 12" src="https://github.com/breadboard-ai/breadboard/assets/45510/d88a7581-a619-4ba8-b163-602142518622">
<img width="307" alt="Screenshot 2024-03-01 at 12 33 35" src="https://github.com/breadboard-ai/breadboard/assets/45510/257e64f4-1a08-4269-b51e-24ab5cb7268c">

**Comment by dglazkov** [comment]
This kit doesn't (yet) have a describer. I hacked it up here for the Agent Kit, need to transplant it to the Gemini Kit:

https://github.com/breadboard-ai/breadboard/blob/ad5c1be938523b2446aee7cd89295d8f76902241/packages/agent-kit/src/hacks.ts#L12-L25
