### ISSUE TITLE
[FR] Tag graphs with UUIDs

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#950]
One of the things we're currently doing with the editor is ensuring that the highlight only operates at the top graph level, which requires a little bit of a dance in the `NodeHighlightHelper` utility. And an incoming feature is for us to update graph nodes with a footer that indicates which subgraph node is actually being handled at a given point.

So it's definitely going to be necessary to pass through the state messages to the editor and have it decide a) which node should be highlighted, and b) what the "footer status" of a given node should be.

So what I'm thinking is this... the various state messages have a `path` property (which we've [talked about deprecating](https://github.com/breadboard-ai/breadboard/issues/342#issuecomment-1894355630)). But what if instead we tag each graph and subgraph with an UUID and use that in the state entries? That way in the editor I can decide if the state change applies to the current graph or not by virtue of the UUID. 

We'd still need some hierarchical information so that I know if a given update applies to a node's subgraph, i.e., "oh yes this most recent entry applies to a subgraph so I'd better update the parent node's footer to show as much".

Does that make sense? @dglazkov

**Comment by dglazkov** [comment]
Per our conversation today, we need an `inspectRun` API.

**Comment by paullewis** [comment]
Yes! Very excited for this one.

**Comment by dglazkov** [comment]
Folding into #963.
