### ISSUE TITLE
Implement API for inspecting/observing board runs

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#963]
Building on the ideas in #950, we need an API similar to Inspector API that would allow easy observing/inspection of a board run. This is a bug to track this work.

This includes adding UUIDs for graphs (mentioned in #950).

- [x] use graph URLs to better identify them
- [x] introduce the concept of "completion" in runs (start/end)
- [x] complete runs after an error occurs (clean up, etc.)
- [x] figure out what to do about `InspectableNodeRunEvent.result`
- [x] consider returning `InspectableNode` in `InspectableNodeRunEvent.node`.
- [x] consider returning `InspectableGraph` from `InspectableGraphStore`.
- [x] consider making `InspectableGraph` the main actor for inspecting runs.
- [x] Write docs.
- [ ] #1015

**Comment by dglazkov** [comment]
@paullewis I now have a very nascent `InspectableRun` interface here:
https://github.com/breadboard-ai/breadboard/blob/14d52203156d325ccccf6c261920b09269f928ee/packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts#L34-L38

It represents the "inspector" instance that's being passed to `bb-ui-controller`. The implementation of this is a hack:

https://github.com/breadboard-ai/breadboard/blob/14d52203156d325ccccf6c261920b09269f928ee/packages/breadboard-web/src/utils/hacks.ts#L14-L28

However, I want to grow it and eventually relocate to the proper place somewhere in `@google-labs/breadboard`. The idea is that this is the instance you can interrogate for various information about the current run.

My question to you is: what would be a super-useful API that this `InspectableRun` could provide to make it easy for you to build the footer you mentioned in #950. And also any other ideas are super-welcome ✨

**Comment by paullewis** [comment]
In an ideal world I would love to have an API that:

1. Tells me what the current graph version is, and where it sits in the overarching graph history: "This is version 21 of 21 and it looks like this at the top level."
3. For each version, we receive a list of runs: "Graph 21 of 21 has seven runs, and run seven looks like this". This would _only_ give me the nodes we ran at the top level becauuuuuuse...
4. For each of the nodes in the run, if there's a subgraph involved I would get an indication in the node's description with – say – a UUID I can use to get more info: "please give me the subgraph run details for this node"
5. When I call into that I get subgraph run information for that subgraph, which looks like the above in that if _it_ has a subgraph on any node I can request that... and so on.

I think that then allows us to:

1. Determine which nodes at which level need to be highlighted.
2. Subgraph rendering and traversal.
3. Undo/redo behavio(u)r for graph versions.

**Comment by paullewis** [comment]
Oh it would also allow us to be more tactical with our history output, which is currently all nodes from everywhere, whereas with this we could emit just the current "graph-level" history entries, which is effectively "run y of version x of (sub)graph".

**Comment by paullewis** [comment]
Another thing that would be nice is that we track all changes, but if we run a particular version that's tagged as a "major" release... a bit semver like. So for the purposes of undo/redo we want all changes, but because that would be verbose if we showed them all, having some sense of grouping seems really helpful.

**Comment by dglazkov** [comment]
Okay, here's a sketch of the types. PTAL, would love your initial thoughts:

https://github.com/breadboard-ai/breadboard/blob/0996a802b04ec7dc3c6d1ce7aadfad85f092f02a/packages/breadboard/src/inspector/types.ts#L331-L441

**Comment by paullewis** [comment]
Forgot to comment earlier, but this looks great. I totally get the concern about the `observe` method, so I wonder if we need to have that elsewhere? Perhaps a top level "run emitter" that we listen to... Pretty much as we do with the current harness. And there's just this API for historical information. If runs are also tagged with UUIDs we can ignore / replace it in the UI if we've already got it from observing the most recent run?

**Comment by dglazkov** [comment]
@paullewis I ran out of time and landed a somewhat half-baked thing. It is used in `activity-log.ts`, and it is fairly easy to remove -- just get back to using `InspectableRun.messages` rather than `InspectableRun.events'.

Primarily, it does not support inline inputs currently. I got secrets to work, but to make inputs go, I need plumb the path for them -- and it's late 😆.

The good news is that this plumbing accounts for graph nesting and all that jazz -- just need to finish it up. My apologies for not finishing this up on time 😞

**Comment by dglazkov** [comment]
Okay, I have _something_. The basics are in the `activity-log.ts`. It's a partial implementation of `InspectableRun.events`:

https://github.com/breadboard-ai/breadboard/blob/dc3560111b84e3f5dbd7f60f69e4df85c30eeafa/packages/breadboard/src/inspector/types.ts#L474-L478

Basically, the idea is that this is a "live" list of events that are happening during the run. Only top-level events are included, plus the events for secrets, bubbling inputs, and bubbling outputs. The last two took a while to get right, but they now work. See "Chat bot 2.0" board for an example. It has both bubbling inputs and outputs.

The object identity of the list changes as it mutates, so it should  "just work" with Lit.

Each item in the list is one of three things:

- `InspectableRunNodeEvent`, which represents a pair of `nodestart` and `nodeend` messages:

https://github.com/breadboard-ai/breadboard/blob/dc3560111b84e3f5dbd7f60f69e4df85c30eeafa/packages/breadboard/src/inspector/types.ts#L394-L432

This one enables handling inputs and secrets: it has a `result` property that contains the original `HarnessRunResult`. This property is nulled out once the `nodeend` message was received. I have a stub of how to potentially ask for input here:

https://github.com/breadboard-ai/breadboard/blob/dc3560111b84e3f5dbd7f60f69e4df85c30eeafa/packages/breadboard-ui/src/elements/activity-log/activity-log.ts#L192-L196

- `InspectableRunErrorEvent`, which represents an `error` message:

https://github.com/breadboard-ai/breadboard/blob/dc3560111b84e3f5dbd7f60f69e4df85c30eeafa/packages/breadboard/src/inspector/types.ts#L434-L441

- `InspectableRunSecretEvent`, which represents a `secret` message:

https://github.com/breadboard-ai/breadboard/blob/dc3560111b84e3f5dbd7f60f69e4df85c30eeafa/packages/breadboard/src/inspector/types.ts#L442-L443

The `InspectableRunSecretEvent` also has a `result` property that can be used to ask and send secrets over.

The way I was imagining secrets and inputs would work in this scenario is that after calling `reply`, the element would send a `breadboardcontinuerun` (or something like that) event that will be picked up by the `bb-main` to resume the asynchronous iteration. Maybe?

What doesn't yet work is that `InspectableRunNodeEvent` will host nested graph runs inside of it. This would allow you to draw all those cool dots for nested graphs and get all the info. I have all the machinery for it, and will work on exposing that next.

Please give it a whirl.

**Comment by dglazkov** [comment]
Ohh that's even better! So you don't actually need the `HarnessRunResult` on the event, right?

**Comment by paullewis** [comment]
Not directly, but the presence of the `result` is useful for differentiating between whether or not the user is needed: https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-ui/src/elements/activity-log/activity-log.ts#L238. 

Also useful for secrets, where once it's been answered the `result` is now null and we know not to spin up an input.

So if we lose that, having some kind of handled boolean would be good.

**Comment by dglazkov** [comment]
Declaring victory 🚢 , splitting off versioning API into its own issue: #1015.
