### ISSUE TITLE
[breadboard-web] Allow users to reset boards after an error

### ISSUE THREAD

**Issue by wfaithfull** [breadboard-ai/breadboard#968]
## Expected Behavior
After a board errors in execution, the user is locked out of all the inputs - buttons, inputs etc are disabled. In order to rerun the board, you need to refresh the page. Typically you want to try the board a few different ways with different inputs - it would be nice to have a "reset" button or similar, or even just automatically reset the state on error. 

## Actual Behavior
![image](https://github.com/breadboard-ai/breadboard/assets/6255193/696aa2b4-ad11-4bbf-8c42-bac2628895e2)

## Steps to Reproduce the Problem

1. Run a board with an undefined input (or some other way to induce an error state)
2. Observe that the web UI has to be refreshed in order to run the board again.

**Comment by paullewis** [comment]
I think this should be fixed now. At least, the update I've done to the UI today allowed me to re-run erroring boards. Do you want to give it a go on your side and let me know?

**Comment by wfaithfull** [comment]
Yes, this works, I can rerun an erroring board. Thank you.
