### ISSUE TITLE
URL for copying board doesn't work

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#975]
When trying to copy a board
![image](https://github.com/breadboard-ai/breadboard/assets/1934/4ec266c0-6ed3-438b-bc37-3da991a7667c)

We get a URL liket this:
https://breadboard-ai.web.app/?mode=list&board=%2Fgraphs%2Faccumulating-context.json

It has the `mode=list` in it. Needs to have `mode=build` instead.

**Comment by paullewis** [comment]
Ah. Yeah, I'll sort that.
